### ISSUE TITLE
Homepage Search input is cleared out when user has already started typing something

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1016]
## Detailed Description

While the homepage is still loading but well displayed, I start to type a search query. If the page load finishes in the meantime, it will discard anything the user would have typed in the meantime.

Behaviour is illustrated by the video below.

![bug gif](https://user-images.githubusercontent.com/138627/27961062-c3e3fc8c-632d-11e7-9514-2323a8b51b8b.gif)

## Context

When I type a query in the search field , I want to lose the content of the input field and be able to start a search when I am done, whatever the state of the component is.

## Possible Implementation

Not sure — make sure upgrading the Vue component does not affect the user experience.

## Your Environment

* Browser Name and version: Chrome evergreen
* Operating System and version (desktop or mobile): macOS 10.something

**Comment by davidbgk** [comment]
When we load the vue component, we should check that the fallback form is empty and otherwise prefill the vue input?

Or use a tremendously fast, accessible and bug free plain old HTML input 🙃 🚎

**Comment by oncletom** [comment]
@davidbgk yes exactly, this is what is proposed in #1019.

My second move intent is to go towards making the HTML form becoming first-class again (as already works without any JavaScript) and to upgrade it with Vue only to provide search autocomplete as a progressive enhancement.

**Comment by oncletom** [comment]
Can be closed now that #1019 has been merged.
