### ISSUE TITLE
Search string spaces encoding when > 2 words

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1017]
## Detailed Description

The spaces in the search string are not decoded when there are more than 2 words (at least 3). Related to #667. 

<img width="585" alt="capture d ecran 2017-07-10 09 57 08" src="https://user-images.githubusercontent.com/119625/28008173-b5c825e4-6556-11e7-88ad-686e1fa06c6a.png">

Thanks @cquest for the report.

## Your Environment

next.data.gouv.fr | udata 1.1.0 | Safari

**Comment by oncletom** [comment]
I suspect it is a duplicate of #987?

**Comment by abulte** [comment]
@oncletom yes, thanks! And I did do a search before submitting 😕.

**Comment by oncletom** [comment]
@abulte no worries — we spotted this bug during the work week with @davidbgk :-D
