### ISSUE TITLE
Resource modification date misleading?

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1018]
## Detailed Description

According to @cquest, and I have to say I agree, the "machine" modification date that we display on the resource box in a dataset may not be the most meaningful information. Shouldn't we display the publication date instead, which can be set by the user and gives an insight about the data itself - as opposed to the document in udata?

<img width="899" alt="capture d ecran 2017-07-10 10 23 31" src="https://user-images.githubusercontent.com/119625/28008940-d99bd5d0-6559-11e7-8753-cef56cdf71db.png">

ping @oncletom 

## Your Environment

next.data.gouv.fr | udata 1.1.0

**Comment by oncletom** [comment]
I totally support the idea of reflecting informations _about_ the dataset content. It does not matter to reflect the update date to fix a typo – it does not make the data fresher.

**Comment by abulte** [comment]
@oncletom Feels like a consensus. Maybe we should rethink the dates displayed in general on datasets and resources, this seems to create some confusion (cf #607 for example - and my discussion w/ @cquest).

**Comment by abulte** [comment]
Discussion w/ @cquest:

> Exemple: https://www.data.gouv.fr/fr/datasets/audiences-quotidiennes-des-principaux-sites-web-gouvernementaux/
> 
> Tu as une date de "Dernière mise à jour de ressource" juste en dessous, elle indiquait 1 janvier 2017... or les ressources ont été modifiées le 5 juillet 2017. C'est ici la date de publication la plus récente dans les ressources et elle me semble donc ok.
> 
> En fait il y a des dates un peu partout et au final on ne sait plus trop ce qui est affiché...
> 
> Sur le dataset:
> 
> - date de création: non modifiable, c'est la date où l'on a créé le dataset sur data.gouv.fr... est-ce que ça apporte une vraie info à quelqu'un qui cherche des données ? Je ne pense pas. On la retrouve quand on clique sur "détail" ce qui me semblerait suffisant.
> 
> - date de modification: non modifiable, c'est la date de dernière modification du descriptif du dataset... pareil je mettrai ça uniquement dans "détails"
> 
> - date de mise à jour de ressource: modifiable (date de publication dans les ressources), celle-la est la plus utile à mon avis elle montre quand on a mis de nouvelles données en ligne
> 
> - on a la couverture temporelle, qui en fait devrait être une agrégation des couvertures temporelles des ressources sauf si on l'indique sur le dataset
> Sur chaque ressource:
> 
> - date de création et de modif: non modifiable, c'est une métadonnée interne de data.gouv, ce n'est pas celle-là que je mettrai en avant (seule cette date de modif est visible actuellement)
> - date de publication: modifiable... c'est plus celle là qu'on devrait rendre visible
> 
> - il manque une couverture temporaire... qui elle pourrait vraiment indiquer à quelles dates se rapporte le contenu de la ressource

**Comment by davidbgk** [comment]
🔥 Warning, this is a hot topic with multiple attempts and none were satisfying so far! The main reason is because there are creation/modification dates for both resources and datasets. Plus those dates are sometimes guessed, sometimes manually specified. And finally, we have the distinction between metadata and data itself.

The only pertinent date (how fresh the data actually is!) is unfortunately unknown for distant resources. We can try to guess it with croquemort but there will probably be too many false assumptions here given the complexity of the task.

We need to consider:

1. the technical part: which dates do we have and how relevant/up-to-date they are? which dates we do not have and we need?
2. the UX part: which ones to display and how?

Any other feedback @odtvince @noirbizarre ?

**Comment by oncletom** [comment]
I can confirm from the first user interviews _displayed dates_ are confusing, not well understood and in some cases mismatch between the _search results page_ and the _dataset page_.

**Comment by odtvince** [comment]
Small data point to add to @davibgk excellent answer: 90% of resources are distant and 10% locally hosted.

**Comment by abulte** [comment]
Migrating this to https://github.com/etalab/data.gouv.fr/issues/154
