### ISSUE TITLE
Search: no territories

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1024]
No territories are indexed (?) and thus no search results for territories. For example https://next.data.gouv.fr/fr/search/?q=le+bon should return `Territoire: Le Bonhomme` like here: https://www.data.gouv.fr/fr/search/?q=le+bon. 

Version : `1.1.0` on `next.data.gouv.fr`

**Comment by abulte** [comment]
@davidbgk can you look into that?

**Comment by davidbgk** [comment]
It looks like territories are not activated on next/demo OR the nightly update didn't upgrade geozones data and so on. Can you confirm @odtvince ?

**Comment by abulte** [comment]
@odtvince will test the gist-stored migration procedure in the upcoming days.

**Comment by abulte** [comment]
Ok on next 1.1.1
