### ISSUE TITLE
Some geo coverage maps are not displayed correctly

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1025]
For example, the datasets for BAN and SIRENE do not show the France coverage on the leaflet widget.

https://next.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/

Version : `1.1.0` on `next.data.gouv.fr`

**Comment by abulte** [comment]
@davidbgk can you look into this one too?

**Comment by davidbgk** [comment]
I think it is related to https://github.com/opendatateam/udata/issues/1024#issuecomment-314769897
