### ISSUE TITLE
Datasets resources are marked as unreachable if the resources checker fails to work

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1042]
## Detailed Description

Yesterday croque-mort was failing for some reasons which means resource checking were failing constantly. The side-effect is resources were marked as unreachable whereas they were reachable.

![image](https://user-images.githubusercontent.com/138627/28360875-a841e922-6c6e-11e7-8814-599bd2eecaae.png)

## Context

When I look at the resources when the resource checker is down, I want to witness no availability warning message, so I can download them.

## Possible Implementation

Error code should be checked more thorougly so as we can distinguish services error from resource checking status.

## Your Environment

* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by odtvince** [comment]
AFAIK we already distinguish between an unavailable link-checking service and an unreachable resource.

The problem described here comes from the way the first case is handeld (red color and black tooltip).

Another problem is the way the second case is handeld (green color with no indication at all that the resource is unavailable; see for instance the docx resource here https://www.data.gouv.fr/fr/datasets/liste-des-ecoles-doctorales-accreditees/ and there http://check.data.gouv.fr/?filter_status=404&filter_domain=data.enseignementsup-recherche.gouv.fr&display_links)
