### ISSUE TITLE
A resource can be created in a format different from the reality

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1045]
## Detailed Description

Someone can create a resource in a dataset in a given format, let's say XML and point it to a resource which is of a different `Content-Type`.

For example, on https://www.data.gouv.fr/fr/datasets/resultats-de-lintegralite-des-elections-depuis-2001/, a single resource is listed as an XML file:

![image](https://user-images.githubusercontent.com/138627/28375622-d71ed27e-6c9f-11e7-8ce7-c29967a05469.png)

Except it returns an HTML page with a directory of resources. There is not even an XML response type when the content is requested as XML:

```bash
$ curl --head -H 'Accept: application/xml' https://www.interieur.gouv.fr/avotreservice/elections/telechargements/
HTTP/1.1 200 OK
Content-Length: 9149
Content-Type: text/html;charset=UTF-8
...
``` 

Places it has been spotted randomly:

| Is | Should be | Where |
|---|---|---|
| XML | NONE | https://www.data.gouv.fr/fr/datasets/resultats-de-lintegralite-des-elections-depuis-2001/ |
| NONE | ZIP | http://www.data.gouv.fr/fr/datasets/impots-locaux-fichier-de-recensement-des-elements-dimposition-a-la-fiscalite-directe-locale-rei-3/ |

## Context

When a content is added in a given format , I want to download a file which respects the advertised format , so I can really use it instead of looking for a needle in an FTP index.

## Possible Implementation

In the admin interface, some heuristics could prevent this kind of behaviours — and could eventually be part of healthcheck metrics.

## Your Environment

* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by davidbgk** [comment]
Or make it easier to declare multiple resources at once when you have a directory full of data!

I mean, the check is informative but it should not prevent from linking to useful data, here I think our interface is the real issue. Referencing all the file within that folder is probably a full day of work, probably more for somebody without any knowledge of the platform. Less controls, more empathy 😉.

**Comment by oncletom** [comment]
Agreed on _easing up dataset creation_.

It's a call for an `udata-http-index-harvester` plugin ;-)
