### ISSUE TITLE
A conversation comment has been published in the future

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1046]
## Detailed Description

As seen on https://www.data.gouv.fr/fr/organizations/institut-national-de-la-statistique-et-des-etudes-economiques-insee/dashboard/

![image](https://user-images.githubusercontent.com/138627/28380356-eb24047e-6cae-11e7-8474-5fdfa31a3d6a.png)

I suspect this event happened within the past hour but because I am in a different timezone (British Summer Time) than the server, the event is considered to happen… in the future.

## Context

When I see a relative time label, I want to see it relative to my timezone, so I don't have to [call the Doctor](https://www.keepcalm-o-matic.co.uk/p/keep-calm-and-call-the-doctor-169/).

## Possible Implementation

N/C

## Your Environment

* Browser Name and version: Chrome evergreen
* Operating System and version (desktop or mobile): macOS Sierra 10.something

**Comment by davidbgk** [comment]
I confirm 😅 TZ issue

<img width="382" alt="capture d ecran 2017-07-19 a 13 26 50" src="https://user-images.githubusercontent.com/3556/28380627-01b32cfc-6c86-11e7-8443-1818d5830b63.png">

**Comment by oncletom** [comment]
It also happens in the profile pages activity stream (looks like it is a pure client-side component).

![image](https://user-images.githubusercontent.com/138627/28530814-e6bc916c-708c-11e7-803d-44093c3424f0.png)

**Comment by oncletom** [comment]
A few remarks:

- it is hard to reproduce locally because all dates are stored accordingly to the timezone of the operating system running `udata` — timezone is not stored either in records or anywhere else;
- the main issue revolves in the fact `i18next.js` declares a `timeago` filter which performs `moment(value).fromNow()` — this is based on the clock of the user and not the clock of the server.

 I see several options:

- using `moment#from(<Date>)` with a date expressed in the timezone of the server;
- using [moment timezone](http://momentjs.com/timezone/) to get the relative date of a given timezone
- configuring the timezone in `udata.cfg` (as `DEFAULT_TIMEZONE = 'Europe/France'` for example) to be able to express the timeliness of a date server and client-side.

**Comment by davidbgk** [comment]
Hard topic, here is [what we did for drone](https://framagit.org/drone/owl#timezone-management-strategy) and it looks to work so far but we don't have that much of quality feedback since the project is 2 months old.

There is probably a valid reason why it is implemented this way but we can still change for expatriates like us /cc @noirbizarre
