### ISSUE TITLE
Resource considered as valid whereas the distant resource is 404

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1048]
## Detailed Description

Cf. https://www.data.gouv.fr/fr/datasets/allocataires-du-rsa-30378531/

![image](https://user-images.githubusercontent.com/138627/28520933-73322b6c-7069-11e7-8879-eea592ee65d7.png)

```bash
$ curl --head http://drees.solidarites-sante.gouv.fr/IMG/xls/rsa_donnees_departementales.xls
HTTP/1.1 404 Not Found
Date: Mon, 24 Jul 2017 11:11:58 GMT
Content-Type: text/html; charset=iso-8859-1
Cache-Control: max-age=3600
Vary: Accept-Encoding
Connection: close
```

## Context

When a resource is displayed as existing , I want to assume it is true , so I can count on the resource to work with.

## Possible Implementation

N/A

## Your Environment

* Browser Name and version: Chrome Evergreen
* Operating System and version (desktop or mobile): macOS 10.12.6 (16G29)

**Comment by davidbgk** [comment]
It may be on the croquemort side. /cc @abulte

**Comment by abulte** [comment]
There is a problem indeed on the udata side, the croquemort response does identify a `404`: `{"charset": "iso-8859-1", "content-disposition": "", "content-encoding": "gzip", "content-length": "198", "content-location": "", "content-md5": "", "content-type": "text/html", "etag": "", "expires": "", "group": "bf664fdb", "last-modified": "", "status": "404", "updated": "2017-09-05T10:40:26.551548", "url": "http://www.drees.sante.gouv.fr/IMG/xls/rsa_donnees_departementales.xls"}`.

The integration is being overhauled though, this will be fixed.

**Comment by oncletom** [comment]
Cool, to be checked on https://next.data.gouv.fr/fr/datasets/liste-des-prenoms-2010-de-digne-les-bains-op/ when (re)deployed.

**Comment by oncletom** [comment]
👍 

![image](https://user-images.githubusercontent.com/138627/30084291-1860a470-9292-11e7-8c1c-7e3ea2e46289.png)
