### ISSUE TITLE
Breadcrumbs are not evenly displayed across pages 

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1056]
## Detailed Description

Several pages do not display the breadcrumb in spite of them being declared in their jinja/html templates:

* Datasets 
![image](https://user-images.githubusercontent.com/138627/28629881-8d5e18b2-7220-11e7-896a-c67cf46d484d.png)
* Organizations
![image](https://user-images.githubusercontent.com/138627/28629899-a149f9f4-7220-11e7-9e80-99ecac76c8d8.png)

## Possible Implementation

Display the breadcrumb unless a good reasons prevails.

**Comment by taniki** [comment]
@oncletom 🆙
