### ISSUE TITLE
Timeline component on user profile page misses some styles

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1058]
## Detailed Description

The `.timeline` component is not styled, probably because the related stylesheet is not embedded.

Plus the `static/user.css` file seems to be missing for some reason.

<img width="605" alt="screen shot 2017-07-26 at 18 35 43" src="https://user-images.githubusercontent.com/138627/28636832-630fcc06-7237-11e7-99ef-9e551bbca35e.png">

Can be seen on https://next.data.gouv.fr/fr/users/alexandre-bulte/

## Possible Implementation

Importing the `.timeline` stylesheet at the Vue component level.

**Comment by abulte** [comment]
All good now 👌 

<img width="1205" alt="capture d ecran 2017-12-07 15 23 42" src="https://user-images.githubusercontent.com/119625/33719994-e193f70c-db62-11e7-9072-fbc65023d876.png">
