### ISSUE TITLE
Improve resiliency when ES is not up-to-date

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#1063]
When there is an issue related to tasks and ES indexation is lagging behind, we should not crash on latest datasets display.

See: https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/126047/

Involved pages:

*  https://www.data.gouv.fr/fr/datasets/?sort=-created
* https://www.data.gouv.fr/fr/datasets/?sort=-last_modified

## Possible Implementation

Check that the response contains valid datasets, not a list of empty dicts:

`u'datasets': <Response: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]>`

Otherwise when we call the `url` template tag on empty dicts it crashes.

**Comment by noirbizarre** [comment]
Some details/explanation.
It only fail in one case: when an object has been deleted and not deindexed yet.
This is why it only fail when putting the latest in first when one has been deleted.
Most often, a cas of moderation, after the dataset has been purge and before the deindexation is done
