### ISSUE TITLE
Add a 'territories' entry in topmenu navbar

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1070]
# Goal

Offer a first-class citizen territory navigation.

# Suggestion

![image](https://user-images.githubusercontent.com/138627/28834913-9c503cfa-76db-11e7-99ec-5c41bd89bff5.png)

**Comment by davidbgk** [comment]
Prior to that, I would improve the "homepage" https://next.data.gouv.fr/fr/territories/
