### ISSUE TITLE
Signpost geo-aware dataset cards in listings

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1072]
# Goal

Indicate the range of geo projections for a given dataset so as we can see which ones are static, and which one can be filtered subsequently.

# Current Situation

Datasets have two form factors, a compact and an expanded card.

![image](https://user-images.githubusercontent.com/138627/29175507-242351f6-7de1-11e7-939e-edfdbe0bd836.png)

![image](https://user-images.githubusercontent.com/138627/29175190-470beef4-7de0-11e7-84cb-5f8049a08ab7.png)

The details of a resource are:

| Name | Visible | Type |
| --- | --- | --- |
| badges | no | `array.<object>` |
| community_resources | no | `array.<object>` |
| created_at | no | `date` |
| deleted | no | `boolean` |
| description | no* | `text` |
| extras | no | `object` |
| featured | no | `boolean` |
| frequency | no* | `enum` |
| frequency_date | no* | `string` |
| id | no | `string` |
| last_modified | no | `date` |
| last_update | no | `date` |
| license | no | `enum` |
| metrics | no | `object` |
| organization | yes | `object` |
| owner | yes | `object` |
| page | no | `string` |
| private | no | `boolean` |
| quality | no | `object` |
| resources | no | `object` |
| slug | no | `string` |
| spatial | no* | `object` |
| tags | no | `array.<string>` |
| temporal_coverage | yes* | `object` |
| title | yes | `string` |
| url | no | `string` |

# Suggestion

![image](https://user-images.githubusercontent.com/138627/28836108-98fd854a-76df-11e7-8067-f5c5746d4579.png)

* in _red_: a geographical projection is available _from → to_ ;
* in _blue_: the territory level is indicated next to the territory name.

![image](https://user-images.githubusercontent.com/138627/28836227-03a2f0a6-76e0-11e7-82f2-8a735f00435b.png)

**Comment by jdesboeufs** [comment]
When we have a France-wide geo-aware dataset, we will often be able to project it to any administrative level (departement, region, commune).
Should be applicable to other countries.

**Comment by oncletom** [comment]
Totally agreed. I wanted to convey a `⑂ <topmost geo level> → <finest geo level>` feeling.

Maybe the tooltip should say `Geographically refine the resources at the Country, Region, Department, County, … City levels`.
