### ISSUE TITLE
Add a territory facet in search results

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1083]
I was wondering how the **spacial converage** concept differs from a **territory**?

![image](https://user-images.githubusercontent.com/138627/29129538-084d8dba-7d1f-11e7-8ebb-e2b4453aaa23.png)

I suspect they are similar/equal concepts so I am unsure about adding a new facet.

@noirbizarre or @davidbgk, do you have any pointer on this?

**Comment by odtvince** [comment]
It is exactly the same thing.

**Comment by oncletom** [comment]
Thanks 🙂
