### ISSUE TITLE
Improve the 'Resource' card in a Dataset page

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1085]
# Current situation

Dataset improvements are happening in #1072.

## Resource

![image](https://user-images.githubusercontent.com/138627/29175243-6a5335e8-7de0-11e7-8709-1a861a768bcf.png)

The details of a resource are:

| Name | Visible | Type |
| --- | --- | --- |
| checksum | no | `string` |
| created_at | no* | `date` |
| description | no* | `text` |
| filesize | no | `integer` |
| filetype | no* | `enum` |
| format | yes* | `string` |
| id | no | `string` |
| is_available | yes | `object` |
| last_modified | yes | `date` |
| latest | no* | `string` |
| metrics | no | `object` |
| mime | no* | `string` |
| published | no* | `date` |
| title | yes | `string` |
| url | no* | `string` |

* these informations are displayed in a popup, after interacting with a resource.

# Ideas Generation

## Idea 1

![shape 12](https://user-images.githubusercontent.com/138627/29175505-23f61e48-7de1-11e7-8e1e-8aff739b81e5.jpeg)

Highlighted features

- show **resource type** (tabular, structured, sheets, shapes)
- show **filesize** in 4 chars
- show **popularity**
- **copy to clipboard** (direct URL or Permalink)

## Idea 2

![shape 12 7](https://user-images.githubusercontent.com/138627/29175498-20f30e7c-7de1-11e7-9bca-8dbdd745d94b.jpeg)

Highlighted features

- show **download** options (full or **geo subset**)
- **copy to clipboard**
- show **filesize** in 4 chars
- show **resource type** (tabular, structured, sheets, shapes)
- show **date coverage**

## Idea 3

![shape 12 4](https://user-images.githubusercontent.com/138627/29175390-d844ad5c-7de0-11e7-8a24-b3de17f506e9.jpeg)

Highlighted features

- show **column count** (for tabular-like resource)
- optional **column documentation**
- show **filesize** in 4 chars
- show **popularity**

## Idea 4

![shape 12 2](https://user-images.githubusercontent.com/138627/29175551-3da35400-7de1-11e7-8a04-1fc19bf6e369.jpeg)

Highlighted features

- **aggregate historical resources** (based on pattern/string distance/whatever)
- optionally show **other resources** (the `...` button)

## Idea 5

![shape 12 5](https://user-images.githubusercontent.com/138627/29175590-59d24938-7de1-11e7-8b43-8a2a9642d2f0.jpeg)

Highlighted features

- show **geo coverage** options
- then applied to **download** or **copy to clipboard**
- show **popularity** (top 10 download this week)

## Idea 6

![shape 12 1](https://user-images.githubusercontent.com/138627/29175344-b66d8596-7de0-11e7-8fe2-5d751c6746af.jpeg)

Highlighted features

- show **features** (type, ower/org, filesize)
- show **description**
- show **resource features** (column count, sheet count, line count)
- show **time coverage**

## Idea 7

![shape 12 6](https://user-images.githubusercontent.com/138627/29175691-a1253188-7de1-11e7-9bf4-5e6f33ccd032.jpeg)

Highlighted features

- show **popularity**
- **aggregate historical resources** (based on pattern/string distance/whatever)
- show **download** options (full or **geo subset**)
- show **usage instructions**

## Idea 8

![shape 12 3](https://user-images.githubusercontent.com/138627/29175367-c95cfb96-7de0-11e7-9730-0a6492ce43a1.jpeg)

Highlighted features

- show **description**
- show **download** options (full or **geo subset**)
- show **license**

**Comment by abulte** [comment]
I ❤️ the "aggregate" idea. I'm 😐 about the popularity. I'm 😄 about the usage instructions and the geo subset download.

**Comment by thimy** [comment]
I agree with the aggregate thing, as I look into the Sirene page I can see a huge list of resources due to daily updates, which most users probably don't need.
Filesize is a must have and a direct download button seems like a good idea.

If we don't display the popularity, maybe we could add a sorting dropdown?

**Comment by oncletom** [comment]
🎉

**Comment by abulte** [comment]
@oncletom ;-) thanks for all the fish!

**Comment by noirbizarre** [comment]
:tada: :confetti_ball:
