### ISSUE TITLE
When URLs are saved, %20 are converted to plus signs

### ISSUE THREAD

**Issue by seiteta** [opendatateam/udata#1126]
## Detailed Description
`%20` in URLs are converted to plus signs when they are saved.

## Exemple
<img width="602" alt="capture d ecran 2017-09-12 a 10 12 40" src="https://user-images.githubusercontent.com/5756228/30315111-2f9947da-97a3-11e7-9b81-e93cdad5c8ad.png">
<img width="644" alt="capture d ecran 2017-09-12 a 10 13 08" src="https://user-images.githubusercontent.com/5756228/30315118-34ee4a8c-97a3-11e7-9050-8f90a85599f4.png">

## Context
When I saved an URL as a ressource, I want it to stay the same, so I can share it on udata even if it contain `%20`.

## Your Environment
data.gouv.fr

**Comment by pblayo** [comment]
According to @noirbizarre's investigation it seems to be a bug in swagger.js.

**Comment by taniki** [comment]
This is also true for any basic field

**Comment by seiteta** [comment]
Thanks 🙏
