### ISSUE TITLE
Could not convert string to float

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1130]
Hello
we get the error could not convert string to float when upload image and try to center it.

https://www.data.gouv.fr/fr/

this error also appears on our server

see attached file

![could_not_convert_string_to_float](https://user-images.githubusercontent.com/30826928/30367179-d2a15aba-986d-11e7-8dcd-898e4a6d88c9.png)

**Comment by abulte** [comment]
@damonzon33 Thanks for this report, I can confirm and reproduce this issue (master and dev). We'll be working on it.
