### ISSUE TITLE
Unable to find existing user on login

### ISSUE THREAD

**Issue by l-vincent-l** [opendatateam/udata#1131]
I can not login, the user is not find when I try to login.

## Detailed Description
With an existing user I can't login.
I have the error : `Specified user does not exist`

## Context

When I login , I want the system to find my user , so I can login.

## Your Environment
I use the master of udata & the master of udata-gouvfr on Ubuntu 16.04.

**Comment by abulte** [comment]
Hey @l-vincent-l, how did you create this user?

**Comment by abulte** [comment]
@l-vincent-l any news on that?

**Comment by abulte** [comment]
@l-vincent-l last chance ;-)

**Comment by abulte** [comment]
Closing this for now, feel free to reopen if you have more details.
