### ISSUE TITLE
Error 500 on duplicate user creation

### ISSUE THREAD

**Issue by l-vincent-l** [opendatateam/udata#1132]
I have a 500 error page when I try to register an already existing user.

## Detailed Description
When I try to sign up with an already registered user I have this error
![image](https://user-images.githubusercontent.com/2757318/30424049-fc4351de-9944-11e7-9c30-992767caab01.png)

## Context

When I sign up with an already registered email, I want to have a human readable error, so I can know I have already registered this user.

## Your Environment
I run udata & udata-gouvfr on master.

**Comment by abulte** [comment]
Is this the same test case as #1131? There must be something strange w/ this user in the first place.

FYI on the latest stable, I do get a readable error message on the form `alexandre@xxx.xxx is already associated with an account.`

**Comment by abulte** [comment]
@l-vincent-l any news on that?

**Comment by abulte** [comment]
@l-vincent-l last chance ;-)

**Comment by abulte** [comment]
Closing this for now, feel free to reopen if you have more details.
