### ISSUE TITLE
metas.publisher is not retrieved in OpenDataSoft harvester

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#1136]
## Detailed Description

Some OpenDataSoft portals (like data.iledefrance.fr) expose data produced by a different publisher.
This information is contained in the `metas.publisher` field.

Example: [API HTTP endpoint](https://data.iledefrance.fr/api/datasets/1.0/validations-sur-le-reseau-ferre-profils-horaires-par-jour-type-1er-semestre-2016) for [Validations sur le réseau ferré : Profils horaires par jour type (1er semestre 2016)](https://data.iledefrance.fr/explore/dataset/validations-sur-le-reseau-ferre-profils-horaires-par-jour-type-1er-semestre-2016/information/).

## Context

When a dataset is harvested on an OpenDataSoft portal , I want to the dataset to be assigned to the relevant organization, so I can retrieve them more easily .

**Comment by abulte** [comment]
@noirbizarre @vince I think this is related to a discussion you had around/with ODS. Can you document here what solution is envisioned, if any?
