### ISSUE TITLE
Unwanted activity on profile timeline

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#1292]
My blank account is displaying a set of misplaced activities.

## Context

![image](https://user-images.githubusercontent.com/27315/33720105-3540f094-db63-11e7-954e-dfac05bdc1e4.png)

https://www.data.gouv.fr/fr/users/tam-kien-duong-3/

## Your Environment

Production

**Comment by taniki** [comment]
After a look at the front-end, I stopped at `udata/core/activity/*`.

The content of the database also give me too much activities for a user that only wrote a comment.

**Comment by abulte** [comment]
Let's remove activity 🚎
