### ISSUE TITLE
Explicit metrics computation

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#1308]
## Detailed Description
Right now, metrics are automagically computed which is problematic because:
- every object modification triggers many comptrics computation
- lots of metrics are computed by tests and slow them down (a big part of the testing time is spent computing metrics)
- this is exponential
- this loads the workers for nothing

## Possible Implementation
Make matrics computation explicit by metric.
This will also ease and structure future new metrics handling

**Comment by quaxsze** [comment]
Due to the massive metrics refactoring released in Udata 2.1.0, this issue is not relevant anymore.
The refactoring pull request is PR [2459](https://github.com/opendatateam/udata/pull/2459).
