### ISSUE TITLE
adds vue error to sentry logging

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#1309]
For example, etalab/data.gouv.fr#42 is not indexed in Sentry and this might indicate that there is a loophole in the reporting system.

**Comment by abulte** [comment]
Good point!

**Comment by taniki** [comment]
It seems that Raven have been silenced since the beginning

```
$ git log -L12,12:site.js 
commit 3a4fc3a8a4d0460b494906c1054f1f09246ecddc
Author: Axel Haustant <noirbizarre@gmail.com>
Date:   Sat Jun 27 11:47:49 2015 +0200

    Migrate home and search js

diff --git a/js/site.js b/js/site.js
--- /dev/null
+++ b/js/site.js
@@ -0,0 +9,1 @@
+// require('raven');
```

**Comment by taniki** [comment]
Keep it open to have a reminder for when we will migrate to vue 2

**Comment by taniki** [comment]
I was confused between `raven` and `raven-vue` plugin. The first part (and global logging) has been restored with #1612

**Comment by abulte** [comment]
Migrating to https://github.com/opendatateam/udata/issues/1312
