### ISSUE TITLE
can't create  topic!

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1325]
Hi,
I just installed the new version 1.2.5. After some tests can't add topic.

thanks for your support.

**Comment by taniki** [comment]
Hi, I have open an issue about the whole topic management (#1282). It is barely usable right now and suffer multiple problems. We plan to fix it in next sprint (next week -> week 1 of 2018).

Closing your issue for sake of redundancy but feel free to come back to the one above.

**Comment by taniki** [comment]
@damonzon33 patched but not yet released. The main issued was that creation requires at least one tag but that was mentionned nowhere and no error notification was issued. Despite that you can still create topic with the buggy UI though.
