### ISSUE TITLE
Recommend complementary datasets through co-occurence in visit logs

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1329]
When a user visits a dataset, it would be nice to suggest to her some other datasets that could be of interest.

One way to do that is to leverage the datasets' visit log (Piwik stats) and determine which dataset is usually being visited after or before the current dataset.

This issue is here to:
- discuss the pertinence of such a feature
- discuss how it could be implemented it on a "data science" level
- discuss how it could be implemented to implement it on the udata "backend" level 
- discuss how it could be implemented to implement it on the udata "frontend" level

_An original idea of @FloSugar._ Poke @taniki.

**Comment by abulte** [comment]
Following a quick meeting with @FloSugar and @taniki, we have some *suggestions*:

- we could test this quickly by providing some static data somewhere (`github.io` or a spare server) that provide the data science part provided by @FloSugar here https://github.com/etalab/piwik_logs/blob/master/datasets_co_occurence.ipynb
- the static data would take the form of multiple json files for the top 30 or 50 datasets `<dataset-id>.json` which contain a list co-occurences for the given dataset: `[(<co-dataset-id-1>, <co-occurence-score>), (<co-dataset-id-2>, <co-occurence-score>)]`
- based on this "API" we would just need a bit of frontend code to call the API asynchronously when viewing a dataset and display "embeds" of the linked datasets (if any). It could be a "Related datasets" section under "Resources", with 3 or 5 max datasets ordered by `co-occurence-score`.

This would allow us to test quickly if the feature is useful / used (don't forget to tag the links to a recommended dataset through Piwik). At a later date we could plug a "real" service behind the API endpoint.

Questions:
- [ ] where shall we prototype this feature? `udata` or `udata-gouvfr`?
- [ ] do we authorize ourselves to host something on `github.io`?
- [ ] ...

**Comment by noirbizarre** [comment]
Agree on prototyping with a static json associating `<dataset_id> => [<co_datasets>]`.
I see 2 ways of doing it:
- prototype in `udata` with feature flag
- prototype in `udata-gouvfr` with a hook in `udata`.
I have a preference for the 2nd choices as it will enable easy feature prototyping on dataset pages for futures features and will allow extension to contribute content on dataset page (ie. geodata widgets, ....).

> do we authorize ourselves to host something on github.io?
I believe it's already the case on `data.gouv.fr`, terms are already taken from github. No needs for github.io, github blobs is sufficient to me (ie. publish the resulting json into the repository)

**Comment by FloSugar** [comment]
Dump #1 : https://github.com/etalab/datasets_reco
