### ISSUE TITLE
[help] How to remove the social share links after a dataset is created?

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1354]
Hello
After creating a dataset or reuse a message appears with links on social networks (see screenshot). I want to delete these links. I tried to edit some files without success. can anyone help me please?

![image](https://user-images.githubusercontent.com/30826928/34710227-bdf508dc-f51a-11e7-8de1-6bc61430974f.png)

**Comment by abulte** [comment]
Hi @damonzon33,

The `<share>` is displaying this. If you remove the line `<share :url="dataset.page" :title="dataset.title"></share>` in `js/components/dataset/created.vue` it should do the trick (for datasets).

Don't forget to recompile the static assets with the `inv assets-build` command.

**Comment by damonzon33** [comment]
@abulte thank you very much for your support!!

**Comment by odtvince** [comment]
Maybe we should make it optional via a configuration directive? I can see a few use cases of uData where generic social networks integration is unwelcome.

**Comment by abulte** [comment]
@odtvince yes, could be useful. I'll create a separate issue.
