### ISSUE TITLE
How to customize password requirements?

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1371]
Hi,

Can you tell me where can I find this information please? 

- Which authentication method is used for the connection on the portal?
Currently password must be at least 6 characters. 

is it possible to change easily:

1- to require a password of at least 8 characters, 
2- to prohibit the reuse of the last 5 passwords, 
3- to require complex passwords?

Thank for your support!

**Comment by noirbizarre** [comment]
Hi :wave: 

udata is using [flask-security](https://flask-security.readthedocs.io/en/latest/) to handle authentication.

There is no apparent easy way to do so, but mattupstate/flask-security#415 gives a lead on how you can.
We are already overriding the default form:
- https://github.com/opendatateam/udata/blob/master/udata/auth/forms.py
- https://github.com/opendatateam/udata/blob/master/udata/auth/__init__.py#L48-L49

So this might be something that can be enhanced

**Comment by damonzon33** [comment]
Hi @noibizarre,

thank you!

**Comment by damonzon33** [comment]
Hi @noirbizarre,

thank you!
