### ISSUE TITLE
Question: Add/delete badges

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1396]
Hello

We want to delete the default badges  (see screenshot) and create our own badges. Can "udata badges" do it and how?

Thank you

![image](https://user-images.githubusercontent.com/30826928/35375723-5ede55b6-01a8-11e8-8398-7175c4b3b3f4.png)

**Comment by noirbizarre** [comment]
Hello,

These are not the default badges but those defined into the `udata-gouvfr` plugin (which are meant for the data.gouv.fr).
You can add your own badges the same way `udata-gouvfr` do: https://github.com/etalab/udata-gouvfr/blob/master/udata_gouvfr/models.py#L33-L37

**Comment by damonzon33** [comment]
Thank you for all your support, we appreciate. 

We were able to create a new badge 

![image](https://user-images.githubusercontent.com/30826928/35390492-f8d3c204-01db-11e8-9721-478442a89e1d.png)

but by removing the others we have an error message and the site does not work anymore (bad gateway).

  "File" /srv/udata/local/lib/python2.7/site-packages/werkzeug/routing.py ", line 1768, in build
     raise BuildError (endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint u'gouven.spd '. Did you mean u'users.show 'instead?

**Comment by abulte** [comment]
Hi @damonzon33, it's probably caused by this line https://github.com/etalab/udata-gouvfr/blob/d1b9d8788c6ab2da33858ec64b020f7b386eb1e4/udata_gouvfr/theme/__init__.py#L41, which is trying to show the datasets linked to the badge "Données de référence", which you don't have anymore.
