### ISSUE TITLE
Add a "functional" type to resources

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1398]
First part of the overhaul of the resources display / navigation.

# What

We should be able to add a "functional" type to resources: is it documentation, stock data, incremental update data...?

# Why

Clarify the display of resources (doc on top?). Pave the way for full resources overhaul (space and time projection...).

# How

1. Identify possible types https://github.com/opendatateam/udata/issues/1398#issuecomment-360478270
2. How to store them?
3. How to display them on front? https://github.com/opendatateam/udata/issues/1398#issuecomment-361247945
4. How do producers fill them on back?
5. How to migrate current data?
6. How to make sure producers do fill the attributes, instead of relying on the default value?

**Comment by abulte** [comment]
# Possible types

- Documentation
- Stock data
- Incremental update data (w/ a frequency?)
- ...

**Comment by noirbizarre** [comment]
## Proposal

Reuse the existing `type` field on resources to add these extra types

**Comment by abulte** [comment]
This is what I have in mind ATM about the display:

<img width="834" alt="paper work 3" src="https://user-images.githubusercontent.com/119625/35513018-f6a4feac-0501-11e8-9df3-db8771ffbb1b.png">

Is this compatible w/ reusing the `filetype` field as @noirbizarre suggested? What do we do with `file`, `remote` and `api` in this case? Display them in their own block? And what about resources that are both `file` and `documentation` for example?

**Comment by noirbizarre** [comment]
Maybe we can have a backward compatibility mapping like it's done for frequencies [here](https://github.com/opendatateam/udata/blob/master/udata/core/dataset/models.py#L56-L61)
To me, the ideal solution is 2 fields:
- a *where* field, ie. `location = {local,remote}`
- a *what* field, ie. `type = {documentation,full,partial,misc}`
The current type field is composite from these 2 concepts

**Comment by abulte** [comment]
Do we really need to ask the producer about `{local, remote}`? It seems like something we can infer from the resource creation / edition alone.

Also, shouldn't API be a possible `what` type field?

In this case we could replace the current field with the new type, with a migration before hand.

**Comment by noirbizarre** [comment]
Yes we can infer this. But this need some UI/UX work on the resource creation and edition.
Currently, the `type` field purpose is to switch the create/edit form fields depending on it.
If we always display the url field and the upload widget, this is not necessary anymore.
The API form is another case but in fact this is the couple `location=remote,type=api`.

So a unique form for the 3 types and a single field `type = {documentation,full,partial,api,misc}` can do the job perfectly.

The backward compatibility table is only here for those who submit legacy types to the API, ie. `type=file -> type=misc`. But it can be managed more simply: is it a known type ? No, so its `misc. This will force API user to update the field value in their usage

**Comment by noirbizarre** [comment]
For the resource list UI, I see something more dynamic which will handle projection and proper pagination/search for datasets with lots of resources.
Agreed on documentation first.

**Comment by abulte** [comment]
@noirbizarre agreed with a more sophisticated interface, especially for projection. Still, maybe we can release a simple v1 ? It probably won't be worse than what we have today, regarding navigating the resources.

**Comment by noirbizarre** [comment]
Yep, let's iterate :+1: 
Maybe switch the stock above the periodical update: as a user, I will download the stock first

**Comment by taniki** [comment]
Yep let iterate (:

A good way to keep both a simple and ordered view should be to propose a "filter bar" that will also be the placeholder for @noirbizarre idea of a more sophisticated navigation.
