### ISSUE TITLE
The ressource markdown description

### ISSUE THREAD

**Issue by damonzon33** [opendatateam/udata#1426]
Hi
When creating a dataset (remote file), the ressource markdown description is not displayed correctly. The description is displayed correctly only during the preview. See screenshot.

![image](https://user-images.githubusercontent.com/30826928/35920560-78c652ec-0c18-11e8-8b12-bb2b758da219.png)

![image](https://user-images.githubusercontent.com/30826928/35920652-b3624aaa-0c18-11e8-9c19-e6d6b0432b4e.png)

![image](https://user-images.githubusercontent.com/30826928/35920864-649bc968-0c19-11e8-9607-c52d4c1ae04f.png)

Udata 1.2.10

Test on data.gouv.fr (1.2.11) same issue

Thanks for your support

**Comment by noirbizarre** [comment]
Yes, this is a known issue and this will be fixed soon.
We are currently refactoring the ressources handling and display, this issue will be fixed in the process.

**Comment by damonzon33** [comment]
thanks

**Comment by noirbizarre** [comment]
Fixed by #1547
