### ISSUE TITLE
Use `metrics.nb_hits` instead of `metrics.views` to count downloads

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1541]
Number of downloads are displayed using `resource.metrics.views` as a source. But `udata-piwik` fills `metrics.nb_hits` instead for this metric. We should use `nb_hits` as a source for display.

**Comment by bzg** [comment]
https://www.data.gouv.fr/fr/datasets/base-de-donnees-accidents-corporels-de-la-circulation uses `metrics.nb_hits` which is always `0`, while `metrics.view` seems to be correct.

Any idea what happens here?  Copying @AntoineAgusti who first reported this.

**Comment by abulte** [comment]
@bzg you're right, one `nb_hits` has been forgotten in https://github.com/opendatateam/udata/pull/1607
