### ISSUE TITLE
Upgrade Authlib v0.6

### ISSUE THREAD

**Issue by lepture** [opendatateam/udata#1566]
Authlib v0.6 is an "alpha to beta" upgrade, but it has some breaking changes.

 Here is an example https://github.com/authlib/example-oauth2-server/blob/master/website/oauth2.py

This is a task for me. I will send a pull request in next week.

**Comment by noirbizarre** [comment]
Great ! Thanks!

**Comment by lepture** [comment]
https://github.com/opendatateam/udata/pull/1572
