### ISSUE TITLE
Password reminder send email fails

### ISSUE THREAD

**Issue by petzlux** [opendatateam/udata#1621]
When the user wants to receive a Password Reminder Email, the following error message is raised:

https://sentry.data.public.lu/share/issue/352e38373831/

Udata 1.3.7

**Comment by abulte** [comment]
This is fixed in https://github.com/opendatateam/udata/pull/1620, we'll release a 1.3.8 ASAP.

**Comment by abulte** [comment]
1.3.8 is out https://github.com/opendatateam/udata/releases/tag/v1.3.8
