### ISSUE TITLE
Logo proposal for UDATA

### ISSUE THREAD

**Issue by ggabogarcia** [opendatateam/udata#1689]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by ggabogarcia** [comment]
I would like to know what you have in mind, how would you like the logo to be?

**Comment by ggabogarcia** [comment]
I'll start making some sketches

**Comment by ggabogarcia** [comment]
Hello @noirbizarre :) , Here is my proposal for the Udata logo, I hope you like it. I was inspired by the [data](https://thumb7.shutterstock.com/display_pic_with_logo/4263988/707440954/stock-vector-data-flow-vector-illustration-digital-information-noise-stream-blockchain-structure-calculation-707440954.jpg) flow, in the binary [code](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAW2NQw10Dpk8Zj2DjS-KKazIIEGh5URlJj8y-hFH4iHmwDJniBw) and I used the initial of the name. I present two alternatives of how the typography would go next to the logo, choose which one you like the most :)
![proposal](https://user-images.githubusercontent.com/35750428/40756388-f8452894-6448-11e8-826b-3897abfbc259.png)

**Comment by noirbizarre** [comment]
Thanks for your proposal ! :bow:

I prefer the 2nd typography proposal: the text to right of the logo.

I'm wondering if the "U" of "UDATA" can be merged with the logo (ie. `<logo>DATA`)

**Comment by thimy** [comment]
I believe both could be used depending on how and where we want to use it. :)
Great work! Thanks for the contribution. 🙌

**Comment by ggabogarcia** [comment]
@noirbizarre Great :), if I'm going to do some tests to see how it looks. As @Thimy says, you can use any version depending on the case, the same applies to the black and white version that works according to the background color if it is very light or very dark :)

**Comment by ggabogarcia** [comment]
@noirbizarre  @thimy  Something like [this](https://i.imgur.com/CzsYO8S.png) ? :)

**Comment by noirbizarre** [comment]
Yes, like this.
But I'm wondering if this is still readable. Maybe the `data` should be closer to the `U`. I dont' know.
This was an idea.

@thimy what do you think ?

**Comment by ggabogarcia** [comment]
Hello sir @noirbizarre , I would like to know if the proposal will be approved, in this way send all the editable files :)

**Comment by thimy** [comment]
I'm not sure one can read `udata`, since the U is much thicker than data. I think I'd prefer the former one.

**Comment by ggabogarcia** [comment]
I also thought the same @thimy , there is a visual imbalance in reading. It would be better to work the logo mark outside the typography

**Comment by noirbizarre** [comment]
Is it possible to have the source files, rendered svgs, pngs... ?
May be as pull request in this repository so we can keep it with the source code ?

**Comment by ggabogarcia** [comment]
Hello sir, here is the link with all the files. svg  png, pdf, eps, Ai. I hope you help them. If need anything else, let me know :).  Link of [font](https://fonts.google.com/specimen/Montserrat)
## [FILES](https://drive.google.com/drive/folders/18TPNh3jmxkBWemECNl6srYc4TBdZ4Ttc?usp=sharing)

![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by noirbizarre** [comment]
Thank you very much !! :heart_eyes: :pray:
