### ISSUE TITLE
logo for udata

### ISSUE THREAD

**Issue by worlwide** [opendatateam/udata#1744]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you.

**Comment by ggabogarcia** [comment]
Hi, @worlwide https://github.com/opendatateam/udata/issues/1689 You should always check the repository first :)

**Comment by worlwide** [comment]
ohh.. sorry.. I did't see

**Comment by ggabogarcia** [comment]
No problem :+1:

**Comment by noirbizarre** [comment]
As we already have a pending logo proposal, I close this issue.

Thanks anyway @worlwide for proposal
