### ISSUE TITLE
User deletion does not give feedback

### ISSUE THREAD

**Issue by MattiSG** [opendatateam/udata#1960]
## Detailed Description

If I am logged in and delete my account, the UI does not give any kind of feedback yet the deletion happens. If I reload the page, I am logged in as the `DELETED DELETED` user.

## Context

I would like to know if my action has succeeded or not.

## Possible Implementation

Flash a confirmation, log me out.

## Your Environment

* Browser Name and version: Safari 12
* Operating System and version (desktop or mobile): macOS

![capture d ecran 2018-11-28 a 13 45 58](https://user-images.githubusercontent.com/222463/49152920-7f927400-f314-11e8-8495-2eedfaa20c86.png)
![capture d ecran 2018-11-28 a 13 46 12](https://user-images.githubusercontent.com/222463/49152925-84572800-f314-11e8-8819-835d4e4f13bb.png)

**Comment by abulte** [comment]
Relates to #1773. Thanks for the feedback!

**Comment by abulte** [comment]
Closing this in favor of #1773
