### ISSUE TITLE
IE11: title field stays required when creating a dataset

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1963]
When creating a dataset on Internet Explorer 11, the title stays flagged as _required_ even though it's filled. The dataset form can not be submitted.

![image001 1](https://user-images.githubusercontent.com/119625/49507988-ecac8900-f881-11e8-8d47-e2bb303116a8.png)

We have multiple confirmation of this bug through different sources.

**Comment by noirbizarre** [comment]
Fixed by #1990
