### ISSUE TITLE
Autocorrect in search field is painful

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#1964]
When searching for a keyword, autocorrect triggers and potentially changes the search query. An example searching for `irve` (which is obviously not a word, and thus triggers autocorrect.

<img width="427" alt="capture d ecran 2018-12-05 15 12 52" src="https://user-images.githubusercontent.com/119625/49519262-e24db780-f8a0-11e8-9209-669ba5e56ace.png">

We should find a way to disable autocorrect on search fields.

Safari, MacOS.

**Comment by taniki** [comment]
https://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input

**Comment by abulte** [comment]
:trollface:

**Comment by noirbizarre** [comment]
When `safari` is the new `IE` :trollface: :trollface:
