### ISSUE TITLE
Les listes de jeux de données et de ressources ne sont pas fiables

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#1977]
Lorsque l'on tente de télécharger la liste des jeux de données `/datasets.csv`, le fichier a un nombre de ligne relativement aléatoire. Le serveur n'émet pas d'erreur visible pour signaler à l'usager que le fichier est incomplet.

Solution possible : ne pas faire du streaming mais en faire un jeu de données en bonne et dû forme.

Cela est également vrai pour la liste des ressources.

https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/648995/

**Comment by abulte** [comment]
We could maybe tackle #2 while handling this.
