### ISSUE TITLE
Unable to add a remote community resource

### ISSUE THREAD

**Issue by Tristramg** [opendatateam/udata#1987]
When adding a community resource, I get stuck on the second panel.

## Context

On the dataset https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-tag-1/

I want to add an `API` type community resource. I get a green validation pop-up and nothing happens.

I attached a screenshot of my form.

The POST request returns a 400 Bad Request.

There are two problems:
* The resource is not added
* There is no error message, even worse, there is a a message saying changes were saved

Here is the payload :

```
{"$pubsub":{"topics":{"updated":[null,null,null,null]}},"$options":{"data":{"filetype":"remote"}},"loading":false,"filetype":null,"format":"gtfs-rt","mime":"application/protobuf","published":"2018-12-17T00:00:00","title":"Gtfs rt bis","type":"api","url":"https://app-be8e53a7-9b77-4f95-bea0-681b97077017.cleverapps.io/gtfs_rt","dataset":"5760038cc751df708cac31a0","organization":{"acronym":null,"class":"Organization","id":"5abca8d588ee386ee6ece479","logo":"https://static.data.gouv.fr/avatars/fb/c57e4ce94f4227811f20c329d3eed0-original.png","logo_thumbnail":"https://static.data.gouv.fr/avatars/fb/c57e4ce94f4227811f20c329d3eed0-100.png","name":"Point d'Accès National transport.data.gouv.fr","page":"https://www.data.gouv.fr/fr/organizations/equipe-transport-data-gouv-fr/","slug":"equipe-transport-data-gouv-fr","uri":"https://www.data.gouv.fr/api/1/organizations/equipe-transport-data-gouv-fr/"}}
```

And here is the response:

```
{"errors": {"filetype": ["Ce champ est requis."]}}
```

## Your Environment

Linux ubuntu 18.10

Firefox 64 and chromium 71

![image](https://user-images.githubusercontent.com/12235/51124345-668b4700-181e-11e9-921a-bb900d645762.png)

**Comment by l-vincent-l** [comment]
This problem is back, I have the exact same error.

**Comment by abulte** [comment]
Reproduced with a distant resource and the following attributes:
- type `API`
- url `https://tr.transport.data.gouv.fr/poitiers/gtfs-rt.json`
- format `json`
- mime `application/json`

**Comment by abulte** [comment]
Reproduced, but a few times and the the problem is gone... This looks like a JS loading (order) issue, hard to track.
