### ISSUE TITLE
Problem with displaying the number of followers in the list of reuses

### ISSUE THREAD

**Issue by pachevalier** [opendatateam/udata#20]
When I go on the list of all [reuses](https://www.data.gouv.fr/fr/reuses/?sort=-followers), the number of followers is always 0. For instance [GRF+](https://www.data.gouv.fr/fr/reuses/grf-application-papier-connecte-et-le-code-du-travail/) has 258 followers but the [list of reuses](https://www.data.gouv.fr/fr/reuses/?sort=-followers) show 0 followers. 

This raises a semantic issue. Should the star symbol stands for "following" (suivre) or "favorite" (favori) ?

**Comment by noirbizarre** [comment]
Right now, it means both.

The uData roadmap plans to split these two concepts:

- follow: stay informed
- star: give credits

But it raises some ergonomics issues.

In the meantime, we will fix the followers display in the search result  and the cards.

**Comment by blaquans** [comment]
Great !
