### ISSUE TITLE
License guessing on "Licence ouverte" could be improved

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2004]
As shown below, the only way to match the licence `lov2` seems to be by feeding the exact title `Licence Ouverte / Open Licence version 2.0` (except for the `/` that can be omitted). Thus, the label `Licence Ouverte Version 2.0` won't trigger a match, although it can be considered a good label.

```
>>> from udata.models import License
>>> License.guess_one('lov2')
<License: Licence Ouverte / Open Licence version 2.0>
>>> License.guess_one('Licence Ouverte Version 2.0')
>>> License.guess_one('Licence Ouverte v2.0')
>>> License.guess_one('Licence Ouverte')
>>> License.guess_one('Licence Ouverte v2')
>>> License.guess_one('Open Licence version 2.0')
>>> License.guess_one('Licence Ouverte version 2.0')
>>> License.guess_one('Licence Ouverte / Open Licence version 2.0')
<License: Licence Ouverte / Open Licence version 2.0>
>>> License.guess_one('Licence Ouverte Open Licence version 2.0')
<License: Licence Ouverte / Open Licence version 2.0>
```

**Comment by noirbizarre** [comment]
Updated in DB on `www.data.gouv.fr`.
`alternate_titles` now contains:
```json
[
    "License Etalab",
    "License Etalab v2",
    "License Etalab v2.0",
    "Licence Ouverte (Etalab)",
    "License Ouverte",
    "Licence Ouverte v2",
    "Licence Ouverte v2.0",
    "Licence Ouverte v2.0 (Etalab)",
    "Licence Ouverte version 2.0",
    "Open Licence v2",
    "Open Licence v2.0",
    "Open Licence version 2.0",
    "Licence Ouverte / Open Licence v2",
    "Licence Ouverte / Open Licence v2.0"
]
```

It might be interesting to expose the `alternate_urls` and `alternate_titles` fields in the API

**Comment by abulte** [comment]
I got the new licences from data.gouv.fr

```
$ udata licenses https://www.data.gouv.fr/api/1/datasets/licenses
➢ Dropping existing licenses
➢ Added license "License Not Specified"
➢ Added license "Open Data Commons Public Domain Dedication and Licence (PDDL)"
➢ Added license "Open Data Commons Open Database License (ODbL)"
➢ Added license "Open Data Commons Attribution License"
➢ Added license "Creative Commons CCZero"
➢ Added license "Creative Commons Attribution"
➢ Added license "Creative Commons Attribution Share-Alike"
➢ Added license "Other (Open)"
➢ Added license "Other (Public Domain)"
➢ Added license "Other (Attribution)"
➢ Added license "Licence Ouverte / Open Licence"
➢ Added license "Licence Ouverte / Open Licence version 2.0"
✔ Done
```

but still no match :-/

```
>>> from udata.models import License
>>> License.guess_one('Licence Ouverte Version 2.0')
```

**Comment by abulte** [comment]
Maybe we're missing a match on `alternate_title` here https://github.com/opendatateam/udata/blob/master/udata/core/dataset/models.py#L161?

**Comment by noirbizarre** [comment]
> Maybe we're missing a match on alternate_title here https://github.com/opendatateam/udata/blob/master/udata/core/dataset/models.py#L161?

This is already matching on `alternate_titles`:
https://github.com/opendatateam/udata/blob/master/udata/core/dataset/models.py#L178

**but**

> It might be interesting to expose the alternate_urls and alternate_titles fields in the API

When you fetch licence on www.data.gouv.fr from the API, you won't get the `alternate_urls` and `alternate_titles` fields so you can't try localy like that.

Fixed in `www.data.gouv.fr` DB, if you want to try locally, you need to manually add the entries in DB.

I'll submit a PR to expose these fields.
