### ISSUE TITLE
Be more accurate and maintainance and governance

### ISSUE THREAD

**Issue by bzg** [opendatateam/udata#2024]
I suggest updating the documentation to reflect the current state of maintainance and governance.

## Detailed Description

- Add udata@data.gouv.fr as a more prominent contact point.
- Fix `index.md` which mentions a voting system that is not actually used.
- Rename `governance.md` as `maintainance.md` with these sections: general maintainance, governance, how to contribute (redirecting to `contribution-guide.md`).

Let me know if this sounds good to you and I'll start working on a PR.

**Comment by noirbizarre** [comment]
Agreed on 2nd et 3rd bullets.

On the mail contact, I'm not sure we want to have an additional email channel. But if this is the case, maybe use `contact@opendata.team` or `udata@opendata.team`.

On the `contribution-guide.md` (and other md files about contribution), maybe we can do something compatible with:
- https://help.github.com/articles/setting-guidelines-for-repository-contributors/
- https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by bzg** [comment]
Thanks @noirbizarre for your feedback.

Okay to use `udata@opendata.team` as the main contact point with the team, provided that `udata@opendata.team` forwards to `udata@data.gouv.fr` instead of forwarding to `data.gouv@data.gouv.fr` as it does now. Agreed?

`contact@opendata.team` does not seem to be used anywhere, either in https://getudata.org or udata's documentation. I suggest simply getting rid of it. I find `udata@opendata.team` better.

On possible enhancements for `contributing-guide.md`, I suggest collecting ideas in another issue.

**Comment by bzg** [comment]
Also, shall we mention https://twitter.com/udata_project somewhere in the documentation? Or does it just belong to https://getudata.org ?
