### ISSUE TITLE
"Choose a file" button is broken when replacing a resource file

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2056]
The button should open a file explorer but does nothing. The drag and drop works fine. 

Tested with Chrome/MacOS, reported by a user.

<img width="651" alt="capture d ecran 2019-03-05 15 08 38" src="https://user-images.githubusercontent.com/119625/53811112-e26d5a00-3f58-11e9-9e13-863972b80fe1.png">

**Comment by noirbizarre** [comment]
Tested and not reproduced on both master and latest release on:
- Google Chromium 73.0.3683.75 (Linux)
- Google Chrome 72.0.3626.121 (Windows 10)
- Mozilla Firefox 66.0 (Linux)
- Mozilla Firefox 63.0 (Windows 10)
- Microsoft Edge 42.17134.1.10 (Windows 10)

So it must be MacOS specific.
@abulte I'll need your help for this one :pray:

**Comment by abulte** [comment]
I can confirm on current master. I will have a look.

**Comment by abulte** [comment]
Actually, it happens only on the "replace file" workflow. Also reproduced on Safari.

**Comment by abulte** [comment]
The `v-el:upload-button` does not seem to kick-in in this case, this is the button DOM:

```
<span class="btn btn-outline btn-flat">
                    Choisissez un fichier de votre ordinateur
                    </span>
```
