### ISSUE TITLE
Discussions API with invalid id or class: improve error and return 404?

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2066]
When using the discussions API to create a new discussion, w/ a payload such as:

```
{
	"comment": "message",
	"subject": {
		"class": "Dataset",
		"id": "5937c5dec751df5a49c153a9"
	},
	"title": "title"
}
```

if the `id` is wrong (for example the id of a non existing dataset) or the `class` is wrong (non existing model), the API will reply with a `400` and this message:

```
{
  "errors": {
    "subject": [
      "Ce champ est requis."
    ]
  }
}
```

This is not very helpful for the caller, since there is indeed a `subject` field in the request.

Maybe we should reply instead with a `404` and a message such as:

```
{
  "errors": {
    "subject": [
      "Could not find an instance of the model <model> with the id <id>."
    ]
  }
}
```

NB: the `404` may not be strictly correct in this case, maybe sticking with `400` is OK and just improve the error message.

**Comment by abulte** [comment]
After investigation, it seems that the `ValidationError` messages raised here https://github.com/opendatateam/udata/blob/master/udata/forms/fields.py#L384 are not bubbled up correctly into the API error.

**Comment by abulte** [comment]
If we remove the `required` validator from https://github.com/opendatateam/udata/blob/master/udata/core/discussions/forms.py#L17, the correct error message will bubble up. `required` seems to take precedence even though it's not involved.

**Comment by noirbizarre** [comment]
I've taken the `400` error path which seems more legit and standard (see #2075)
Was tricky because of `WTForm` which is hiding all error message when a `required` error is triggered.

**Comment by abulte** [comment]
poke @l-vincent-l

**Comment by l-vincent-l** [comment]
:clap: never thought it would be that hard!

**Comment by noirbizarre** [comment]
Me neither !
