### ISSUE TITLE
Change of `SITE_TITLE` in config file doesn't really matter

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#2160]
https://github.com/opendatateam/udata/blob/b647a9c30403644ce7b3d3f7a9702c2c40f20603/udata/templates/macros/metadata.html#L8

I had to spend some time on this one. When you change your udata instance title, you will have to edit the `site` collection in mongodb. Should we replace that `current_site.title` with `config.SITE_TITLE` since it is already used in the same file ?

**Comment by abulte** [comment]
Maybe remove all references to `site.title` (and keywords?), delete the field(s) from the model and the DB and see if anything breaks.

**Comment by taniki** [comment]
https://github.com/opendatateam/udata/commit/73beb39c39fb9e45085e4f50e133c9966408e9da#diff-e97d85d0e7b36b3d0e54b69589db032b

Initial intent was certainly to keep python front-end and javascript admin in sync
