### ISSUE TITLE
Admin: Inconsistency of list of items on deletion

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#2216]
In the admin, there is two differents behavior when one delete an item from a table view:

1. item stay visible. eg.: delete a reuse in the `dashboard` part
2. item is hidden. eg.: delete a dataset or a reuse in the `site` part

The initial behavior is to hide deleted item but this is neither always true nor something we want. I think it would be best to display deleted item with a visual mark like enclosing title with a `<del>` tag.

**Comment by taniki** [comment]
Issue: this is complicated for main type of objects (datasets, reuses, ...) because of architectural tweaks related to search indexation.

I propose do make API changes when search indexes are not involved i.e. at least on the list of harvesters because that case raised the ux issue.

**Comment by noirbizarre** [comment]
Fixed in #2228
