### ISSUE TITLE
Conflict between id and slug can cause major trouble

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#2300]
If one use id of an existing dataset as a title of a new dataset, the URI will resolve to the new dataset. This can be a major issue if some users are using id instead of slugs for sake of stability.

Example:
- https://next.data.gouv.fr/fr/datasets/53699fe4a3a729239d206227/
- https://data.gouv.fr/fr/datasets/53699fe4a3a729239d206227/
- https://next.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/

**Comment by abulte** [comment]
Probably a good idea to do this on organisations too.

**Comment by abulte** [comment]
Cf (at least) https://github.com/opendatateam/udata/blob/fdec5338c0e4193b5ef6391304c45723b5e970e5/udata/core/organization/models.py#L93

**Comment by taniki** [comment]
The same problem might also be risen in the API.
