### ISSUE TITLE
Update Serbian translations

### ISSUE THREAD

**Issue by kojicz983** [opendatateam/udata#2348]

**Comment by abulte** [comment]
Hi, translations are updated regularly. Crowdin makes automated Pull Requests like https://github.com/opendatateam/udata/pull/2346. Please reopen this issue if you have a more specific problem description.

**Comment by kojicz983** [comment]
@abulte we are waiting for months now for our updated translations to be approved on Crowdin platform. I've tried to contact you guys there but with no success.

So, pls approve our updated translations and merge it with a new release.

Thank you

**Comment by abulte** [comment]
> we are waiting for months now for our updated translations to be approved on Crowdin platform

The approval status is not necessary AFAIK. For example, your untranslated translation of "A set of boolean parameters to toggle" is included since at least two releases https://github.com/opendatateam/udata/blob/v1.6.16/js/locales/udata.sr.json#L8. Please indicate which translations are missing from the latest release, if any.

>  I've tried to contact you guys there but with no success.

I'm sorry about that. As you can see we can be reached here.

**Comment by kojicz983** [comment]
@abulte Thank you for a fast replay

Here is just an example

[https://github.com/opendatateam/udata/blob/v1.6.16/js/locales/udata.sr.json#L32](https://github.com/opendatateam/udata/blob/v1.6.16/js/locales/udata.sr.json#L32
)

[https://crowdin.com/translate/udata/7/en-sr#q=%D1%85%D0%B0](https://crowdin.com/translate/udata/7/en-sr#q=%D1%85%D0%B0)

As you can see 6 months ago we proposed a change in one of the translations and all of us voted for it.

Pls, guide us on how to make this process faster and easier.

**Comment by abulte** [comment]
Ok I see the problem now, this is about changing existing translations, not only adding new ones.

I just approved every suggestion on translations with an issue opened. Please tell me if it's OK, I have no way of judging if the translations are OK by myself.

If it's OK for you, we'll include those translations in the next release.

Also, I will look into making you capable of approving translations for the Serbian language, if possible. Would you be interested in that? Can I ask what you're using udata for (Serbien open data portal?) and what's your position/role on the project?

**Comment by kojicz983** [comment]
That is perfect.
Pls, if it's possible to add me as translations approver for the Serbian language.

I'm a software developer in the operations department at UNDP Serbia. One of the projects I'm working on is Open Data. 

We are using udata as Serbian national open data portal.

The closest description of my role is the open data portal team lead.

**Comment by abulte** [comment]
Great! You're now a proofreader for the Serbian language on the project. It should give you permission to approve translations.

Ping me when everything is OK with the translations and I will merge the crowdin PR.

I'm glad we sorted this out!

**Comment by kojicz983** [comment]
I think we are all set and done. :)

Feelings are mutual.

Thank you so much!
