### ISSUE TITLE
filename is overriding title on API upload

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#2357]
Currently when one is uploading a file, the filename is used as a title. That is a bit problematic when one want to set a proper title or have already set one (behavior on update is to replace previous title with current filename). This is also problematic when want to download a file from the api, it forces to parse the request content in order to find out the original name (and the extension).

This has already been fixed when uploading a resource via the UI cf. #196.

## propositions

- store filename and title separately
- use filename when no title is provided

## other

This might help to partially resolve #2141 for future resources: you might infer that if a ressource is not a file because it has no filename then it is an url and then an access point and not a download point. Also you might want to show a “visit page” button instead of “download” button.

**Comment by abulte** [comment]
https://github.com/opendatateam/udata/issues/2086
