### ISSUE TITLE
Removing a user causes server error when accessing its ressources

### ISSUE THREAD

**Issue by quaxsze** [opendatateam/udata#2456]
Removing a User before removing every one of its comments or discussion causes the datasets to fail loading because of a mongoDB error:

<img width="722" alt="Capture d’écran 2020-02-11 à 11 12 49" src="https://user-images.githubusercontent.com/57526019/74227805-8611cf00-4cbf-11ea-8da9-d278740b02d5.png">

**Comment by abulte** [comment]
How did you remove the user? A brutal delete in the DB would to that. Using the correct method on the model or the backoffice shouldn't.
