### ISSUE TITLE
Implement PKCE via Authlib

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2479]
As noted in #2298, we're currently allowing implicit grant OAuth workflow for SPA apps. This workflow has been deprecated and replaced by PKCE. We should look into implementing PKCE on the server side via Authlib https://docs.authlib.org/en/stable/specs/rfc7636.html?highlight=#module-authlib.oauth2.rfc7636.

**Comment by lepture** [comment]
Here is my change for adding PKCE in example-oauth2-server: https://github.com/authlib/example-oauth2-server/commit/a36b9e08270b12c82efe767f6792cab986c8a51e
