### ISSUE TITLE
Handle CORS on error responses from API

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2481]
CORS is currently not supported on all errors responses (`40x`, `50x`) from the API.

This currently means:
- epic trouble when trying to use the API from a SPA: you never know why your request failed
- it's _impossible_ to implement chunked upload from a SPA, since `UploadStatus` is handled as an exception and thus does not support CORS — the process will fail after the chunk is uploaded

**Comment by quaxsze** [comment]
CORS are now handled by Flask-CORS since #2510 
This seems to have fixed the issue.
