### ISSUE TITLE
Error when drag and dropping file for resource

### ISSUE THREAD

**Issue by quaxsze** [opendatateam/udata#2483]
When adding a resource on the drag and drop module in the admin, it fails frequently saying the variable `this.$upload` is undefined.

Sentry's event id is [243e70a18d244742864daee00f243959](https://sentry.data.gouv.fr/etalab/www-datagouvfr/issues/660260/events/8373351/)

**Comment by JulienParis** [comment]
copy of the error in Sentry => 

```
this.$uploader is undefined
```

```js
// in => ./js/mixins/uploader.js?2cb0**** in apply at line 225:17
             * Trigger file upload on drop complete
             *
             * See: http://docs.fineuploader.com/branch/master/features/drag-and-drop.html#processingDroppedFilesComplete
             */
            on_dropped_files_complete(files) {
                if (this.canDrop) {
                    this.$uploader.addFiles(files); // this submits the dropped files to Fine Uploader
                }
            },
            /**
```

**Comment by JulienParis** [comment]
In Sentry => 520 errors events from 130 users 

copy of the tags recorded by Sentry => 
<img width="232" alt="Capture d’écran 2020-06-16 à 15 28 47" src="https://user-images.githubusercontent.com/21986727/84780772-41d46980-afe6-11ea-8bb7-5ba403c9a333.png">

**Comment by JulienParis** [comment]
benchmark // 

- current library for uploads : 
  - [FineUploader](https://fineuploader.com/) : pb : no longer maintained

- potential candidates to replace : 
  - [dropzone](https://www.dropzonejs.com/#) : pb : needs vue2 ? 
  - [dropzone tuto](https://medium.com/practicaldesign/fileuploader-with-vue-273b64e61609)

**Comment by JulienParis** [comment]
### The steps to reproduce the bug are the following (thx to Mathilde) : 

----
1. go to a dataset public page you have the admin rights upon [example here](https://demo.data.gouv.fr/fr/datasets/upload-bug-d-d-2483/)
<img width="948" alt="Capture d’écran 2020-06-19 à 10 12 04" src="https://user-images.githubusercontent.com/21986727/85112094-695d4900-b215-11ea-856e-1166961361d7.png">

-----
2. click directly on the "add a ressource"/"ajouter une ressource" block 

---
2bis. you are redirected to the admin page and the drag & drop zone is automatically opened
<img width="951" alt="Capture d’écran 2020-06-19 à 10 14 31" src="https://user-images.githubusercontent.com/21986727/85112299-b5a88900-b215-11ea-8f8c-87bad3b54c17.png">

-----
=> consequences :

----
- **BUG 1** : trying to drag & drop a file into the zone generates an error
<img width="952" alt="Capture d’écran 2020-06-19 à 10 15 31" src="https://user-images.githubusercontent.com/21986727/85112375-d4a71b00-b215-11ea-84e7-e555b75c00d1.png">

---
- **BUG 2** : the "choose a file" button does not respond

----
My guess so far is if we succeed in instantiating the `$uploader` we could fix both of these bbugs, without having to recode a new drag & drop uploader for now...

**Comment by JulienParis** [comment]
The `dataset.vue` component is calling other components as follow : 
```
└─ dataset.vue (view)
    : from : udata/js/views/
    │
    └─ list.vue (loaded as ResourceList component) 
         : from : udata/js/component/dataset/resource/
         │
         └─ add-modal.vue
              : from : udata/js/component/dataset/resource/
              │
              └─ form.vue
                  : from : udata/js/component/dataset/resource
                  │
                  └─ uploader.js
                      : from : udata/js/mixins
```

But the order in which components start and finish to load are the following : 

1. dataset.vue > init()
1. dataset.vue > beforeCompile()
1. uploader.js > init()
1. list.vue > init()
1. uploader.js > beforeCompile()
1. list.vue > beforeCompile()
1. uploader.js > ready()
1. list.vue > ready()
1. add-modal.vue > init()
1. add-modal.vue > beforeCompile()
1. **uploader.js** > init() _- repeating init()_
1. form.vue > init()
1. uploader.js > beforeCompile()
1. form.vue > beforeCompile()
1. **uploader.js** > ready()
1. form.vue > ready()
1. add-modal.vue > ready()
1. dataset.vue > ready()

**Comment by JulienParis** [comment]
Another and similar error exists when you need to update a dataset's resource directly from the public page... So to reproduce that error those are the steps :  

-----
1. you need to be logged ... then go to a dataset public page you have the admin rights upon [example here](https://demo.data.gouv.fr/fr/datasets/upload-bug-d-d-2483/)

![Capture d’écran 2020-06-22 à 18 01 39](https://user-images.githubusercontent.com/21986727/85309202-8d898600-b4b2-11ea-85b4-92dee3c16709.png)

---
2. on a resource click on "edit this resource / modifier cette ressource" ... you are redirected to the backoffice w/ a resource modal opened...

![Capture d’écran 2020-06-22 à 18 01 50](https://user-images.githubusercontent.com/21986727/85309261-a134ec80-b4b2-11ea-8a5a-4df47be43884.png)

---
3.  ... then click on "edit"


![Capture d’écran 2020-06-22 à 18 02 09](https://user-images.githubusercontent.com/21986727/85309278-a7c36400-b4b2-11ea-9dea-4af930304de9.png)

--- 
4. ... then click on "replace this file"

![Capture d’écran 2020-06-22 à 18 02 22](https://user-images.githubusercontent.com/21986727/85309291-ad20ae80-b4b2-11ea-941c-f860c361ebdf.png)

---
5. ... finally try a drag and drop a file to the zone => it doesn't work, nothing happens => a progress bar **should** appear and apply the download
