### ISSUE TITLE
System jobs not launched after udata>=2.0.0 upgrade

### ISSUE THREAD

**Issue by mayjolux** [opendatateam/udata#2489]
Hi from Luxembourg!

We finally finished our migration from udata 1.6.20 to udata 2.0.0  and now even to 2.1.0.
However, I noticed that our Harvester Jobs (purging deleted datasets, organizations too) were not launching since I migrated from 1.6.20 to 2.0.0. If I define them in the System Tab of the admin panel, they show up as usual and get their default cron job planification of 0 0 * * *, but they don't get launched at that time.

If I go now on the machine and trigger the launch with the "udata harvest launch" method, the harvest is started without a problem, no error messages, everything just works fine. I don't know if I am missing something specific in the changes of udata 2.0.0.

In your breaking changes of udata 2.0.0 you say: "Deprecated celery tasks have been removed, please ensure all old-style tasks (pre 1.6.20) have been consumed before migrating" Since those harvest jobs are launched by celery workers I think it has maybe something to due with this? Maybe you have some additional information or encountered the same kind of problems during your migration?

In another small question, concerning the harvester creation and its planification, if I program the planification to 0 2 * * * for example in the UI of EDIT>Planification, the following is added to the cron expression b'0' b'2' b'\*' b'\*' b'*', which generates an error. I am not quite sure why this happens, do you have an idea?

Thanks for any help in this matter!

**Comment by abulte** [comment]
Hi,

What is the output of `udata job scheduled`? You might also want to look at the state of your celery queues and see if the jobs are correctly consumed (`udata worker status` might help).

> In another small question, concerning the harvester creation and its planification, if I program the planification to 0 2 * * * for example in the UI of EDIT>Planification, the following is added to the cron expression b'0' b'2' b'*' b'*' b'*', which generates an error. I am not quite sure why this happens, do you have an idea?

Looks like a bug from the migration to python3. We're not using this feature lately, that's why we did not catch it. Can you fill a different issue for this?

**Comment by mayjolux** [comment]
This is the output of the udata job scheduled:

b'Harvest Harvester IGSS': harvest(5ede2bd69e975616ca4ceab7) ↦ 0 10 * * *
b'Harvest Harvester STATEC': harvest(5ede0215ae9201709ddf956f) ↦ b'0' b'0' b'*' b'*' b'*'
b'Generate hourly Piwik metrics': piwik-current-metrics ↦ 0 * * * *
b'Generate yesterdays Piwik metrics': piwik-current-metrics ↦ 0 0 * * *
b'Purge les jeux de donn\xc3\xa9es supprim\xc3\xa9s': purge-datasets ↦ 0 3 * * *
b'Purge les organisations supprim\xc3\xa9s': purge-organizations ↦ 0 0 * * *
b'Purge les reuses supprim\xc3\xa9s': purge-reuses ↦ 0 0 * * *

The queues are empty:
Queue "default": 0 task(s), Queue "high": 0 task(s), Queue "low": 0 task(s)

**Comment by abulte** [comment]
This looks pretty good, apart from the issue you raised.

Do you have a `beat` worker started? `ps aux|grep beat` on your main worker machine might help.

**Comment by mayjolux** [comment]
There are actually two beat workers running with the following configs for the celery worker:
/srv/udata/bin/python3.7 -m celery worker -c 1 -Q high -A udata.worker --loglevel=INFO --beat --logfile=/var/log/udata-celery/worker-high%I.log --pidfile=/var/run/udata-celery/worker-high.pid --hostname=high@ip-XXX-XXX-XXX-XXX

**Comment by abulte** [comment]
Are you _sure_ the beat worker is correctly started/running? We got bit by that a few times.

If you are, I'm out of idea for now :-/ Maybe check the logs from the worker, if you can see anything it would be useful. If you have a Sentry integration there might be some useful stuff there too.

**Comment by abulte** [comment]
Of course you can try restarting the workers, but I guess you already done that.

**Comment by abulte** [comment]
Wrong automated closing :-)

**Comment by abulte** [comment]
I guess this is ok? Do not hesitate to reopen if needed.
