### ISSUE TITLE
Wrong cron expression of harvester planification since py3 migration

### ISSUE THREAD

**Issue by mayjolux** [opendatateam/udata#2490]
Concerning the harvester creation and its later planification, if you program the planification to 0 2 * * * for example under the UI of EDIT>Planification, the following is added to the cron expression:

b'0' b'2' b'\*' b'\*' b'*', which generates an error later on.

Seems to be related to the python3 migration. Additionally:
This does not happen if you go with the default cron expression and it does not happen if you schedule it via the "udata harvest schedule"

**Comment by abulte** [comment]
Re #2489

**Comment by abulte** [comment]
Fixed by https://github.com/opendatateam/udata/pull/2493
