### ISSUE TITLE
Some linkified urls are including the app server name

### ISSUE THREAD

**Issue by JulienParis** [opendatateam/udata#2496]
In a dataset's text, an url written in a markdown format is transformed into a `<a>` tag but its `href` attribute contains the app server name within the url... 

You can check an example of this behaviour here => [test Bleach dataset](https://www.data.gouv.fr/fr/datasets/dataset-test-1/)

## Detailed Description
 if you  write a text as : 
```
link 03 : [rte-france-03.com](rte-france-03.com)
```
you get on the client side something like : 
```
<p>link 03 : <a href="https://www.data.gouv.frrte-france-03.com">rte-france-03.com</a></p>
```
... which is wrong and not desired behaviour I guess : it shoud not contain `www.data.gouv.fr` before `rte-france-03.com` in the `href` attribute

## Possible Implementation
check PR #2486

**Comment by abulte** [comment]
What does the markdown says about that? I wouldn't be shocked if `http(s)://` was mandatory in a markdown link.

**Comment by abulte** [comment]
Cf https://pad.incubateur.net/WK9dDgvlSZSP--G059UVMA?both for a test on another markdown parser.

**Comment by abulte** [comment]
What's your suggested behaviour BTW?

**Comment by JulienParis** [comment]
the wrong `netloc` value is injected/recreated at this moment => https://github.com/opendatateam/udata/blob/01534c65a40d564edae39675df16dd790121c8c8/udata/frontend/markdown.py#L46

**Comment by JulienParis** [comment]
> What's your suggested behaviour BTW?

```
link 03 : [rte-france-03.com](rte-france-03.com)
```
should produce 
```
<p>link 03 : <a href="https://rte-france-03.com">rte-france-03.com</a></p>
``` 
> + a `rel="nofollow"` attribute but that's described in [another issue](https://github.com/opendatateam/udata/issues/2497)

**Comment by abulte** [comment]
Cf https://gist.github.com/abulte/9b4ffe706f4667a13db3265bec14538e

So I think the real issue is that we don't add a `/` between data.gouv.fr and the (internal) URL when we need one. Other than that it's OK. #2497 is not an issue either.

**Comment by JulienParis** [comment]
What should it produce then ?

**Comment by abulte** [comment]
To be clear,  `[rte-france-03.com](rte-france-03.com)` should yield `<p>link 03 : <a href="https://www.data.gouv.fr/rte-france-03.com"></p>`

**Comment by JulienParis** [comment]
but following that logic `[www.rte-france-06.com](www.rte-france-06.com)` should also yield `href="https://www.data.gouv.fr/rte-france-03.com"`

**Comment by abulte** [comment]
nope, to https://www.data.gouv.fr/www.rte-france-06.com

**Comment by abulte** [comment]
It's not a question of SEO, it's that we shouldn't try to guess if a link is internal or external. If the user wants an external, she uses `http(s)://`, if not we consider it as an internal link and enforce our site name in front of it.

**Comment by abulte** [comment]
This is what GitHub does in the end. They keep it as a relative link but we can't because we need the `nofollow`.

<img width="507" alt="Capture d'écran 2020-06-15 13 37 57" src="https://user-images.githubusercontent.com/119625/84653304-7cb69e80-af0d-11ea-9949-2124b187cfb3.png">

**Comment by JulienParis** [comment]
> nope, to https://www.data.gouv.fr/www.rte-france-06.com

sorry I rectified my comment above, but ok I get it now...

**Comment by JulienParis** [comment]
Github behaviour just to compare... 

```
- alone : [lalala.com](lalala.com)
- www : [lalala.com](www.lalala.com)
- http : [lalala.com](http://lalala.com)
- https : [lalala.com](https://lalala.com)
```

- alone : [lalala.com](lalala.com) => local
- www : [lalala.com](www.lalala.com) => internal
- http : [lalala.com](http://lalala.com) => external
- https : [lalala.com](https://lalala.com) => external

So yes Bleach behaves another way and induce an external url, that is a root cause of our mutual miscomprehension on this matter :)

**Comment by abulte** [comment]
> So yes Bleach behaves another way and induce an external url, that is a root cause of our mutual miscomprehension on this matter :)

It's not Bleach, it's our `nofollow_callback` function. And it's because we enforce a `nofollow`, like the function name says.

**Comment by JulienParis** [comment]
I did an update on a live test => https://www.data.gouv.fr/fr/datasets/bleach-test-002/

**Comment by JulienParis** [comment]
what confused me was `link-txt-01` and `link-txt-02` are not currently behaving as you mentionned above but `link-md-01` is (approximatly  modulo the `/`)...

**Comment by JulienParis** [comment]
Anyway I'll work on a solution giving the exact same behaviour than GH + adding `nofollow` if link is external, seems easier to describe that way... is that ok for u @abulte @quaxsze ?
