### ISSUE TITLE
Some linkified urls does not include `nofollow`

### ISSUE THREAD

**Issue by JulienParis** [opendatateam/udata#2497]
In a dataset's text, an url written in a markdown format is transformed into a `<a>` tag which does not contain the `rel="nofollow"` attribute

You can check an example of this behaviour here => [test Bleach dataset](https://www.data.gouv.fr/fr/datasets/dataset-test-1/)

## Detailed Description
 if you  write a text as : 
```
link 03 : [rte-france-03.com](rte-france-03.com)
link 06 : [www.rte-france-06.com](www.rte-france-06.com)
```
you'll get on the client side something like : 
```
<p>link 03 : <a href="https://www.data.gouv.frrte-france-03.com">rte-france-03.com</a></p>
<p>link 06 : <a href="https://www.data.gouv.frwww.rte-france-06.com">www.rte-france-06.com</a></p>
```
... which contains an error described [here](https://github.com/opendatateam/udata/issues/2496) but also does not include the `rel="nofollow"` attribute we need  

## Possible Implementation
check PR #2486

**Comment by abulte** [comment]
We don't need `rel="nofollow"` if we consider those links as internal links. So this _could_ *not* be an issue.

**Comment by taniki** [comment]
luckily there is a trailing slash, between data.gouv.fr and the internal link, which avoids a potential abuse.
