### ISSUE TITLE
Format of an uploaded file w/ a name containing more than one dot is wrong

### ISSUE THREAD

**Issue by JulienParis** [opendatateam/udata#2504]
A file with a filename containing more than one dot (`.`) displays a wrong format.

## Detailed Description

An uploaded file named `Capture d’écran 2020-06-16 à 15.28.47.png` is going to be displayed as a file with a `28.47.png` format, instead of a plain `png` format.

### Screenshot => 

Example of an uploaded resource on a dataset

<img width="935" alt="Capture d’écran 2020-06-16 à 16 04 50" src="https://user-images.githubusercontent.com/21986727/84785175-77c81c80-afeb-11ea-877a-2bb35ee61b99.png">

**Comment by JulienParis** [comment]
similarities but quite diferent from #1045 and #986

**Comment by abulte** [comment]
Closing in favour of https://github.com/opendatateam/udata/issues/2504, which has better visibility for our users

Duplicates https://github.com/opendatateam/udata/issues/2504
