### ISSUE TITLE
Harvest job collection grows too big

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2563]
```
$ du -sh mongo/mongodump-2020-10-31/udata/harvest_job.bson
17G	mongo/mongodump-2020-10-31/udata/harvest_job.bson
```

We probably don't need to store all the history of the harvest jobs, a few months should be enough. I'm pretty sure we had something somewhere to prevent this but if we had it's clearly broken.

A scheduled job to truncate the job history could be a good solution.

**Comment by quaxsze** [comment]
Job found in source code https://github.com/opendatateam/udata/blob/7e04eb3531c724a94cc85a92223f3fd3e89ca5ad/udata/harvest/tasks.py#L64
