### ISSUE TITLE
Discussions: implement backend sort to match frontend options

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata#2576]
There is a sort option on the frontend on discussions but it's not wired to the backend. The API has a `sort` option but it does not seem able to do what the frontend asks (cf below).

We should implement those sort options on the backend and wire the frontend to them.

<img width="204" alt="Capture d’écran 2020-11-20 à 11 13 59" src="https://user-images.githubusercontent.com/119625/99788630-a65d9c80-2b21-11eb-8bc9-db15baa7b7e4.png">

**Comment by quaxsze** [comment]
After checking the API, the endpoint would be able to perform what the frontend asks using its sort argument :
`http://dev.local/api/1/discussions/?sort=-created`
`http://dev.local/api/1/discussions/?sort=-discussion.posted_on`

It now needs to be wired to the frontend.
