### ISSUE TITLE
DCAT harvester does not correctly guess the licence

### ISSUE THREAD

**Issue by restuccia** [opendatateam/udata#2618]
## Context
The following organisation https://www.data.gouv.fr/fr/organizations/communaute-dagglomeration-du-niortais/ set up a DCAT harvester from their ArcGIS portal https://donneespubliques.niortagglo.fr/

The harvester works correctly, for example https://donneespubliques.niortagglo.fr/datasets/7c46b68b64c8493c84bf340eaf5d6cce_0/ ➡️ https://www.data.gouv.fr/fr/datasets/decheterie/

But the licence is not harvested correctly, and as a result the dataset on the udata portal has no licence.

Stream here: https://donneespubliques.niortagglo.fr/data.json?filter[source]=niort_agglo.data

## Possible Implementation

I suppose this is due to how the harvester "tries to guess" the licence ([as specified here](https://github.com/opendatateam/udata/blob/master/docs/harvesting.md)), and in this specific case, the dataset in the source catalogue has "Licence Etalab" as licence, which is not correctly matched to the "Licence Ouverte 2.0".

Maybe add a rule in the licence-guessing code that matches any licence containing the word "Etalab" to the "Licence Ouverte 2.0" ?

## Your Environment

udata 2.7.1
udata-gouvfr 2.6.2

**Comment by abulte** [comment]
This should be fixed with the above link @jdesboeufs — `etalab-2.0` has been added to alternate titles on https://www.data.gouv.fr/api/1/datasets/licenses/.

**Comment by abulte** [comment]
Documentation is updated https://doc.data.gouv.fr/moissonnage/licences/, this should fix the issue. If not, please reopen!
