### ISSUE TITLE
App return 404 after following all the steps for develompent environment

### ISSUE THREAD

**Issue by nikolakovacevic4github** [opendatateam/udata#2707]
After following all the steps described in the documentation on the new Ubuntu 20, the app returns 404 Not found

## Detailed Description

 following all the steps described in the documentation https://udata.readthedocs.io/en/stable/development-environment/
leads to command inv serve
and after that it is written: When you have the development server running, you can open your browser to http://localhost:7000/. Everything should be up and running!

But app returns 404 after curl http://localhost:7000
curl http://localhost:7000
<*!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"*>
<*title>404 Not Found</title*>
<*h1>Not Found</h1*>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

## Context

Further clarification in the documentation about this situation will be very useful for new developers in this project. 

## Possible Implementation

Edit docs for covering this scenario 
## Your Environment

Ubuntu 20.04

**Comment by nikolakovacevic4github** [comment]
Thank you maudetes!
I have tried to install udata-front following instructions from it's readme, but I am failing to install it or set it for development.
Should I open a similar issue in it's repository?
Is there a possibility for more direct communication, since I might have need for more help with developing on udata-front?

**Comment by maudetes** [comment]
The documentation has been updated to reflect the udata 3 and 4 changes. See install instructions for udata-front : https://udata.readthedocs.io/en/stable/getting-started/#install-udata-front.

I'm closing this issue. Don't hesitate to re-open if relevant.
