### ISSUE TITLE
Support all dublin core frequencies

### ISSUE THREAD

**Issue by nicolas-bonnel** [opendatateam/udata#273]
The DCAT schema uses frequencies defined by dublin core : http://dublincore.org/groups/collections/frequency/

For better interoperability between data catalogs published on the Web, is it possible to support all these frequencies ?

Triennial [freq:triennial]
Biennial [freq:biennial]
Annual [freq:annual]
Semiannual [freq:semiannual]
Three times a year [freq:threeTimesAYear]
Quarterly [freq:quarterly]
Bimonthly [freq:bimonthly]
Monthly [freq:monthly]
Semimonthly [freq:semimonthly]
Biweekly [freq:biweekly]
Three times a month [freq:threeTimesAMonth]
Weekly [freq:weekly]
Semiweekly [freq:semiweekly]
Three times a week [freq:threeTimesAWeek]
Daily [freq:daily]
Continuous [freq:continuous]
Irregular [freq:irregular]

**Comment by noirbizarre** [comment]
Thanks !

omeone else already suggested this and it will be done soon ;)
