### ISSUE TITLE
Make the whole API support CORS

### ISSUE THREAD

**Issue by nicolas-bonnel** [opendatateam/udata#274]
Some endpoints such as /spatial support cross origin request, while others do not, such as /datasets.

**Comment by nicolas-bonnel** [comment]
I was calling the wrong endpoint, didn't put a slash at the end of the path in the URL. /datasets/? is working while /datasets? results in a 301 response.

But the redirect response does not have headers to allow CORS.

**Comment by noirbizarre** [comment]
The behavior that trigger a redirect is trigger by flask itself: http://flask.pocoo.org/docs/0.10/quickstart/#variable-rules (See the Unique URLs / Redirection Behavior section)

About the cors, It's handled by https://github.com/flask-restful/flask-restful/blob/master/flask_restful/utils/cors.py
If something is wrong with it maybe a an issue or a pull-request is required.
It may be somewhat related to https://github.com/flask-restful/flask-restful/issues/65

**Comment by nicolas-bonnel** [comment]
The location header is in the redirect response, it's all the Access-Control-* header that are missing.

**Comment by abulte** [comment]
I agree this (missing CORS in redirect response) should be handled at the `Flask-Cors` level. They're talking about it a bit here https://github.com/corydolphin/flask-cors/issues/128#issuecomment-198453999 but I do not think they support this yet. In the mean I'm closing this, feel free to reopen if needed.
