### ISSUE TITLE
`udata-search-service` dependency is not mentioned in Getting Started, although seems to exist

### ISSUE THREAD

**Issue by tboye** [opendatateam/udata#2796]
## Detailed Description

When following [Getting Started](https://udata.readthedocs.io/en/stable/getting-started/) doc, I faced `ERROR: Missing URL for search service` error when trying to launch udata. I fixed it by installing and configuring [`udata-search-service`](https://github.com/opendatateam/udata-search-service). It would be great to fix it either in documentation or in the environment setup flow (if it's possible).

## Context

When I follow Getting Started, I want to avoid preventible issues, so I can start quicker.

## Possible Implementation

**Option 1** -- add `udata-search-service` installation step to Getting Started.
**Option 2** -- eliminate dependency on `udata-search-service` in the environment setup flow.

## Your Environment

Not relevant

**Comment by maudetes** [comment]
Thank you for this ticket.
Indeed, `udata-search-service` is optional and you shouldn't be faced with an error when launching udata without it.
I've created a fix in this PR in https://github.com/opendatateam/udata/pull/2797.
