### ISSUE TITLE
Which service corresponds to RESOURCES_ANALYSER_URI ?

### ISSUE THREAD

**Issue by freesoul** [opendatateam/udata#2804]
We are using the udata-search-service, and everything seems to work fine, except that on resource addition/modification/elimination, we do not get the events published, and therefore nothing gets updated into ES. 

The reason why the events are not published, is that we are missing the service defined by the configuration variable RESOURCES_ANALYSER_URI, which by default is localhost:8000.

Our current solution, is to have a cron which reindexes everything, but this is not ideal.

Could we find somewhere this service please?

**Comment by freesoul** [comment]
Ok, the data is actually reindexed, it's just there is 30min delay in our metric update job

I guess we don't need that RESOURCES_ANALYSER_URI

**Comment by maudetes** [comment]
Hello, thank you for the update and closing the ticket!

Indeed, `RESOURCES_ANALYSER_URI` is not required for udata-search-service.
It has been added to publish events happening at the resource level to a different service. In our case, this currently points to our crawler (and analyser) [udata-hydra](https://github.com/etalab/udata-hydra), on which we're currently working.
