### ISSUE TITLE
DCAT minor compatibility issues

### ISSUE THREAD

**Issue by AlainVagner** [opendatateam/udata#2854]
We have recently analysed the compatibility of the DCAT implementation in udata 4 with the latest [DCAT-AP specification (2.1.1)](https://github.com/SEMICeu/DCAT-AP/releases/tag/v2.1.1) and we have found some minor issues.

## Detailed Description
- on a dataset object, the property `dct:publisher` is not available when requesting the metadata of a specific dataset, ex:  https://www.data.gouv.fr/api/1/datasets/5b7ffc618b4c4169d30727e0/rdf.xml but is available for example on the site catalog: https://www.data.gouv.fr/catalog.rdf
- there is a typo in the property `dcat:byteSize`, which is named `dcat:bytesSize` in udata.
- the property `dct:description` is mandatory but missing on the `Catalog` object, be it on the main catalog https://www.data.gouv.fr/catalog.rdf or on the catalog of an organization 
- on the object `PeriodOfType`, the properties `dct:startDate` and `dct:endDate` have the type `xsd:date` but the specification requires `xsd:dateTime`. 

## Context
The DCAT-AP compatibility is important for the interoperability between data portals in Europe.

## Your Environment
This has been tested on data.gouv.fr.

**Comment by AlainVagner** [comment]
Hi, thanks for your feedback!
There is a checker here: https://data.europa.eu/mqa/shacl-validator-ui/ but I am not totally sure how to use it, it seems to be quite permissive compared to the specification.

I have mainly checked the documentation and schema available there https://github.com/SEMICeu/DCAT-AP/releases/tag/v2.1.1 inside source-code.zip, the file DCAT-AP-2.1.1/releases/2.1.1/dcat-ap_2.1.1.pdf

**Comment by AlainVagner** [comment]
@maudetes I have checked with our team and I'm afraid we won't be able to contribute with a PR on this topic. Sorry for that.

**Comment by maudetes** [comment]
I've had a go at these issues in https://github.com/opendatateam/udata/pull/2860.
You can take a look if that seems okay for you.

In the case of `PeriodOfType`, the datatype `xsd:date` is automatically added since we're actually exposing dates and not dateTimes. The way I understand the specification, `xsd:date` is allowed.
In the spec:
> rdfs:Literal typed as xsd:date, xsd:dateTime, xsd:gYear or xsd:gYearMonth

But we should probably use `dcat:startDate` instead of `schema:startDate`?
Do you agree on this interpretation?

**Comment by AlainVagner** [comment]
Thanks a lot for these changes! 
I misread the spec for the class `PeriodOfTime`, and you are right, `xsd:date` is ok there. I don't have access to a computer at this time, so I am not really sure what `schema:`  was about, but the spec mentions `dcat:`.
