### ISSUE TITLE
Unclear field name/description in /topics

### ISSUE THREAD

**Issue by maukoquiroga** [opendatateam/udata#2902]
## Detailed Description

Hi! Taking a look at the `/topics` documentation [here](https://guides.data.gouv.fr/publier-des-donnees/guide-data.gouv.fr/api/reference/topics), there is the following field name/description that is unclear:

```
deleted string The organisation identifier
```

## Context

Clarifying the description of the field helps me and other users to implement servicers relying on the `/topics` ressource.

> When I read the `/topics` documentation , 
> I want to understand its fields' descriptions, 
> so I can use it.

## Possible Implementation

Correcting the `deleted` description.

## Your Environment

* Browser Name and version: LibreWolf-105
* Operating System and version (desktop or mobile): OS X Sonoma 14.0

**Comment by maudetes** [comment]
Hello, thank you for the issue.

Indeed, the `deleted` api field is useless and has been removed in https://github.com/opendatateam/udata/pull/2903.
When deleting a Topic, you should use `DELETE https://www.data.gouv.fr/api/1/topics/{topic}/`, which will remove the topic immediately.

**Comment by maukoquiroga** [comment]
Thanks!
