### ISSUE TITLE
Ajouter des permissions admin pour accéder à /api/1/users

### ISSUE THREAD

**Issue by ThibaudDauce** [opendatateam/udata#3044]

**Comment by ThibaudDauce** [comment]
@maudetes Qu'est-ce qu'on fait pour le suggest? Est-ce que du coup on empêche uniquement les requêtes sans query `q` pour les non admin? Est-ce qu'on met une limite minimum de caractères pour accepter la requête avec une recherche?

**Comment by maudetes** [comment]
Il y a plutôt /api/1/users/suggest/?q= de dédié je pense (sans pagination notamment). A vérifier cependant l'usage de /api/1/users si jamais
