### ISSUE TITLE
expose licenses API / Allow external licenses

### ISSUE THREAD

**Issue by nicolas-bonnel** [opendatateam/udata#314]
Currently, the way how licenses work is not clear. A dataset have a license which is a string but we cannot use any value we want, it seems only codes stored somewhere are allowed ("cc-by", "fr-lo", ...).

The list of these codes is not available with an API and cannot be manipulated with a third-party app.

Moreover, it would be great to be able to use an URL for this field so that a license stored elsewhere can be used.

**Comment by abulte** [comment]
Hi,

I don't know if your question is about the web interface or the deployment of `uData`. If the latter, you can use the command `udata licenses https://www.data.gouv.fr/api/1/datasets/licenses` to import the licenses used by `uData` from a URL.

If not, please do not hesitate to reopen this issue and maybe give us more details about your use case.
