### ISSUE TITLE
[DOC] Mail configuration link to Flask-Mail settings is dead

### ISSUE THREAD

**Issue by rv2931** [opendatateam/udata#3215]
In the documentation https://udata.readthedocs.io/en/stable/adapting-settings/, the link to Flask-Mail configuration settings is dead
pointing to https://pythonhosted.org/flask-mail/

Maybe this link should be : https://flask-mail.readthedocs.io/en/latest/ ?

**Comment by maudetes** [comment]
Thank you for the notice. See this PR for a fix: https://github.com/opendatateam/udata/pull/3216
