### ISSUE TITLE
Problem with filtering

### ISSUE THREAD

**Issue by pachevalier** [opendatateam/udata#34]
When I try to filter datasets by "spatial coverage" (see this [example](https://www.data.gouv.fr/fr/datasets/?q=g%C3%A9olocation+des+communes&geozone=country-subset%2Ffr%2Fmetro)), I've got inconsistent results. For instance, when I ask for "France métropolitaine", I've got very local datasets as output such as Brocas datasets. 

Where does this come from ? Is it because spatial coverage is missing for those datasets ? In that case, I think that we should drop those datasets from the output.

**Comment by noirbizarre** [comment]
Nop, When you filter on "France métropolitaine", it keeps every datasets contained in "France Métropolitaine"
As "Brocas" is part of "France métropolitaine", it is part of the search result.

It's more significative with smaller filters: When you filter on "Ile de France", you have datasets from Paris.

**Comment by blaquans** [comment]
Ok, but how can I look for datasets which concerns all "France métropolitaine" ?
