### ISSUE TITLE
docker-compose up [locking out]

### ISSUE THREAD

**Issue by dina2000** [opendatateam/udata#468]
Command docker-compose up [locking out]
## Detailed Description

Process locked during docker-compose up
## Context

Download and install Docker images which takes a while depend of your connection.
## Possible Implementation

In order to deploie uData application,

I read your deploiement instruction on this link

http://udata.readthedocs.io/en/stable/system-dependencies/#mongodb-elasticsearch-and-redis 

After docker installation, i continued the process typing the command docker-compose up. Command who download and install Docker images which takes a while depends of your connection.

I noticed that the process is locked

[docker-compose up.txt](https://github.com/opendatateam/udata/files/276232/docker-compose.up.txt)
## Your Environment

Windows 7
Virtualisation support Ok
Dokcer installation Ok

**Comment by abulte** [comment]
Hi @dina2000, do you still experience this issue?

**Comment by abulte** [comment]
@dina2000 feel free to reopen if problem persists.
