### ISSUE TITLE
Problem on step 2 when creating a new Dataset

### ISSUE THREAD

**Issue by rblmdst** [opendatateam/udata#486]
Problem on step 2 when creating a new Dataset
![bug_dataset_1](https://cloud.githubusercontent.com/assets/2565606/15900456/21f0fb2a-2d8f-11e6-9812-60f7705070c5.png)
## Detailed Description

When creating a new dataset, in the second step (Décrivez votre jeu de données) when the first time when you click on the  **Suivant** button to go to the step 3 it works, but when you click on the **Précédent** button to go back to the step 2, and then click the **Suivant** button it doesn't work.
The console shows the message:
missing required params: dataset
even if you fill all the fields. The field **Couverture temporelle** get the focus and nothing happened again on the page.
The **Couverture spatiale** become inactive with a text **Couver** when you a value in as on the image

**Comment by noirbizarre** [comment]
This should have have been fixed by #482 and #469 on dev and backported on master by #502 .
Can you confirm that I can close the issue.

**Comment by noirbizarre** [comment]
And by #484 (also backported in #502)

**Comment by abulte** [comment]
I confirm this is fixed. Please reopen the issue @rblmdst if the problem persists.
