### ISSUE TITLE
Upload of a new Dataset files doesn't work

### ISSUE THREAD

**Issue by rblmdst** [opendatateam/udata#487]
When creating a new dataset, on the step 3 , nothing happened when you clicked on the buttons to upload file that at related to a dataset.
No error message in the console when you clicked on the buttons.
But the console shows 
Uncaught TypeError: Cannot read property 'validate' of undefined
when you clicked on **Next** button

**Comment by petzlux** [comment]
are you on the right branch ? ie `dev` ?

**Comment by rblmodeste** [comment]
Yes of course

**Comment by noirbizarre** [comment]
Weird, I just tested it. I will try to reproduce the issue.

**Comment by noirbizarre** [comment]
This should have have been fixed by #482 and #469 on dev and backported on master by #502 .
Can you confirm that I can close the issue.

**Comment by jphnoel** [comment]
Tested in a local environment, with the dev branch, and the bug is not reproduced.
