### ISSUE TITLE
Add the ability to filter on several organizations

### ISSUE THREAD

**Issue by tportier** [opendatateam/udata#525]
The API should be able to make a filter on several organizations in the API.
It would permit to create a child catalog based on https://github.com/DepthFrance/udata-js in which we could search for datasets filtered on a selection of organizations.

The API datasets request could be extended to accept several organization id in the organization option such as 534fffb3a3a7292c64a78129,551959f6c751df6682057c91,558bef88c751df1fd9a453b9

**Comment by davidbgk** [comment]
That issue depends on the following ongoing pull-request: https://github.com/opendatateam/udata/pull/524
Once we'll have the new elasticsearch DSL it will be way easier to implement that feature.

**Comment by noirbizarre** [comment]
@davidbgk you're faster than me ! I'm working on it right now
