### ISSUE TITLE
Switch from microdata to JSON-LD

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#536]
## Context
Today, we embed some metadata with the microdata format, i.e. directly within the DOM. We use these metadata both for internal use (in the JS of the dataset frontend) and for external use (SEO). 

## Detailed Description
When we display the dataset page, we need to parse the DOM to retrieve all the metadata, for the modals, and to be able to check the availibility of the resources with Croquemort. 

Let us consider now a dataset with many resources (typically 300, which is a real use cas, encountered in Luxembourg): it does work, from a functional point of view, but it is much too slow.

## Possible Implementation
With [JSON-LD](https://developers.google.com/schemas/formats/json-ld) we should have much better performance.

Moreover, for W3C and Google, microdata is considered as deprecated, and should be replaced by JSON-LD.

Lastly, using microdata makes the templates verbose and harder to maintain.

**Comment by davidbgk** [comment]
The performance issue was found by @opendatalu when there are more that 300 resources for a given dataset.

**Comment by davidbgk** [comment]
Relevant files:

* https://github.com/opendatateam/udata/blob/dev/js/microdata.js
* https://github.com/opendatateam/udata/blob/dev/js/front/dataset/index.js
* https://github.com/opendatateam/udata/blob/dev/udata/templates/dataset/display.html#L58

**Comment by jphnoel** [comment]
Other relevant files:
- https://github.com/opendatateam/udata/tree/dev/specs/fixtures/microdata
- https://github.com/opendatateam/udata/blob/dev/specs/microdata.specs.js

**Comment by jphnoel** [comment]
Even more other relevant files:
- https://github.com/opendatateam/udata/blob/dev/udata/templates/dataset/resource/list-item.html
- https://github.com/opendatateam/udata/blob/dev/udata/templates/organization/display.html
- https://github.com/opendatateam/udata/blob/dev/udata/templates/reuse/display.html
- https://github.com/opendatateam/udata/blob/dev/udata/templates/user/base.html
