### ISSUE TITLE
Bug when navigating in next/previous during the creation of a new dataset

### ISSUE THREAD

**Issue by jphnoel** [opendatateam/udata#540]
As a registered user, I want to add a new dataset:
1. https://next.data.gouv.fr/en/admin/dataset/new/
2. I select a user and click on 'Next'
3. I fill the mandatory fields : "title", "description", "Update frequency" and I click on 'Next'
4. I click now on Previous

Problem: I do not come back to the step 3. I am stuck on the step 2 (see screenshot).
![screen_shot_2016-04-11_at_6 51 35_pm](https://cloud.githubusercontent.com/assets/7070530/18712765/20e0988e-8010-11e6-8856-1e50fa18ac65.png)

Proposal: use vue-router to navigate through the steps

**Comment by abulte** [comment]
Ok on `master` as of today.
