### ISSUE TITLE
Tags too short or with special characters silently prevent from submitting a dataset

### ISSUE THREAD

**Issue by jphnoel** [opendatateam/udata#563]
Environment:
- I run the server in a local development environment
- I use the branch `dev`

Steps:
- I submit a dataset
- In the step 2, I set the the mandatory fields
- In the step 2, I set a tag which contains special characters (`aaa$`) or is shorter than 2 characters (`a`)
- I click on `Next`

Unwanted behaviour:
- I get stuck

Explanation:
- On the [server side](https://github.com/opendatateam/udata/blob/dev/udata/forms/fields.py#L309), I got a validation error, which leads the browser to fail silently.

Possible solutions:
- Prevent the user from entering a tag which does not match what is expected by the server
- Convert the tags on the client side so that they match what is expected by the server
- Convert the tags on the server side so that they match what is expected by the server
- Display an error message on the client side explaining that the tags are not well formatted
- Live with this bug until we remove WTForms (since it seems to be related to the WTForms machinery)

**Comment by noirbizarre** [comment]
The expected behavior is 3: tag should be normalized on the server side for any client (admin, API...).
So if I submit `My tag with A spécial character` it should be accepted and normalized into `my-tag-with-a-special-character`.

**Comment by abulte** [comment]
This is correctly handled now, except for the notification "Changes saved" which should not be shown. I'm opening another issue for that.

<img width="792" alt="capture d ecran 2017-11-14 14 44 54" src="https://user-images.githubusercontent.com/119625/32782969-78a5f21a-c94a-11e7-889a-1d68255ba5c1.png">
