### ISSUE TITLE
Prevent multiple membership creation

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#600]
## Detailed Description

Prevent a same user to be added multiple times as member of the same organization.
## Context

When a user perform many clicks on membership request, many requests are issued.
The same issue occurs on request validation and so many memberships are created.
It doesn't prevent udata to handle permission correctly but this is ugly and inconsistent.
## Possible Implementation

I think there is 2 action levels:
- client-side: prevent multiple clics on buttons and give visual feedback on pending submissions
- server-side: ensure only one membership request can be open by couple User/Organization and only one membership can exists for the same couple
## Your Environment

Bug present on https://www.data.gouv.fr (aka. on master).
Might already be solved on `dev` branch. Need to check first.

**Comment by abulte** [comment]
@noirbizarre I just tested on dev. This is mostly OK: only one membership request is created on the backend even when submitted multiple times (`201` status code then `200`). The only problem is that the membership request popup on the front does not close when the request is submitted.

**Comment by abulte** [comment]
@noirbizarre nope, no problem anymore with the latest version of `dev`. I'm closing this, feel free to reopen if I missed something! Fixed by #955 I think.
