### ISSUE TITLE
Uniformization of the front/back Markdown rendering for tables

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#604]
## Context

When I add a table to the backend interfance, I want to see it rendered as a table on the frontend, so I can propose a nice visualization of the data.

## Possible Implementation

Both implementations rely on CommonMark, the front is generated by Python so check if both libs follow the same version and if tables have to be activated.

**Comment by davidbgk** [comment]
<img width="490" alt="capture d ecran 2016-11-03 a 14 43 49" src="https://cloud.githubusercontent.com/assets/3556/19980334/fcf2cae2-a1d3-11e6-9b17-081c24490c47.png">
<img width="247" alt="capture d ecran 2016-11-03 a 14 43 40" src="https://cloud.githubusercontent.com/assets/3556/19980342/ff459bee-a1d3-11e6-8ee2-9e571a28d380.png">
<img width="916" alt="capture d ecran 2016-11-03 a 14 43 59" src="https://cloud.githubusercontent.com/assets/3556/19980346/014258b0-a1d4-11e6-9c79-4e6b27a3e485.png">

**Comment by abulte** [comment]
@davidbgk apparently `CommonMark-py` does not support tables https://github.com/rtfd/CommonMark-py/issues/28. It looks like `Python-Markdown' does though https://pythonhosted.org/Markdown/extensions/tables.html, should we consider switching?

**Comment by davidbgk** [comment]
@abulte you're right, tables are not part of the [CommonMark spec](http://spec.commonmark.org/0.27/), we should measure if tables are really in use before switching to something else if pertinent. It's biased because the current implementation doesn't encourage the use but anyway we have data so let's use it :)
