### ISSUE TITLE
Error when displaying "Last modified" date, displays "Created at" instead

### ISSUE THREAD

**Issue by Flightan** [opendatateam/udata#607]
## Detailed Description
It should display the correct last modified date for a dataset.

## Your Environment
https://www.data.gouv.fr/fr/datasets/caracteristiques-techniques-des-sites/

<img width="848" alt="screen shot 2016-11-09 at 10 27 52" src="https://cloud.githubusercontent.com/assets/1475946/20133582/64aaf0d6-a668-11e6-8fb1-26e214b40408.png">
<img width="337" alt="screen shot 2016-11-09 at 10 28 02" src="https://cloud.githubusercontent.com/assets/1475946/20133589/6f7bfee2-a668-11e6-9b7c-d1ee330a4204.png">
<img width="340" alt="screen shot 2016-11-09 at 10 28 09" src="https://cloud.githubusercontent.com/assets/1475946/20133593/72fe65aa-a668-11e6-9968-364919670e27.png">
<img width="557" alt="screen shot 2016-11-09 at 10 34 47" src="https://cloud.githubusercontent.com/assets/1475946/20133599/78486e5c-a668-11e6-8de0-2a8c3232d3f0.png">

**Comment by jphnoel** [comment]
You maybe misunderstood the meaning of the different dates.
Actually, a dataset contains several resources, and the dates of the dataset are independent of the dates of the related resources.
On the left of the screen, you have the dates of the resources. 
On the right of the screen, you have the dates of the dataset.
Thus, it is possible that the dataset and the resource have been created on the 18/02/2016, and the dataset has been modified on the 9/11/2016.
If this is the case, the pictures attached to the issue are consistent and there is no bug.

**Comment by abulte** [comment]
Hi @Flightan, did @jphnoel answer your question? If not, feel free to reopen the issue.
