### ISSUE TITLE
Problème lié à la couverture temporelle des jeux de données

### ISSUE THREAD

**Issue by romtal** [opendatateam/udata#614]
## Detailed Description

Le problème est le suivant : lorsque je veux mettre à jour la fiche donnant les détails de l'annuaire statistique de la DGFiP, je ne parviens pas à modifier la couverture temporelle. En effet, avant modification, elle indique les dates 01/01/2004 au 31/12/2012. Désirant modifier la date du 31/12/2012 en 31/12/2013, le message "La date de fin doit être après la date de début" est affiché, et cela quelque soit le mode de modification de la date ou le navigateur (IE ou Firefox). En revanche, j'ai pu modifier sans aucun problème la date de mise à jour (08/11/2016). 

## Context

When _____ , I want to _____ , so I can _____ .

## Your Environment

* Browser Name and version
[data_gouv_fr_pb_maj_dates.docx](https://github.com/opendatateam/udata/files/604296/data_gouv_fr_pb_maj_dates.docx)
:
* Operating System and version (desktop or mobile):

**Comment by jphnoel** [comment]
I could not reproduce the bug on the dev branch. Actually, I can set any date, even an end date prior to the start date, without getting any message.
@noirbizarre do you think this is an old bug which has been solved on the dev branch but not on the master branch ?

**Comment by noirbizarre** [comment]
I think it's partially solved on dev branch, I'll submit a fix ASAP.

@romtal Screenshot in docx file?! :fearful: :astonished: Come on, you're better than that ! :stuck_out_tongue_winking_eye:
