### ISSUE TITLE
Provide a minimal doc about deployment and operation of udata

### ISSUE THREAD

**Issue by jphnoel** [opendatateam/udata#624]
Based on the feed-back provided by Luxembourg and Serbian teams during the OGP summit, I want a documentation with at least the following content:

- Integration of Udata with NginX
- A template of Ansible script or Docker file (even if the user does not use these technologies, it would show briefly how Udata is deployed in a real situation)
- Integration of Udata with S3 (which actually consists simply in mounting an S3 folder in Linux)
- Configuration of of the jobs, such as 'purge-datasets'
- Configuration of the harvesters
- Explanation of how the metrics work, typically how they are updated and how they interact with Piwik
- Integration of Croquemort within Udata and explanation of how Croquemort is used by udata
- Explanation of how to use geozones work, with a simple example of it
- Examples of simple customization files (modification of the CSS, HTML templates, etc...)
- Configuration of the mail sending
- Simple sketch explaining how Udata interact with the main external components (Mongo, ElasticSearch, reverse-proxy, etc.)

**Comment by abulte** [comment]
@noirbizarre I think we're quite OK regarding this now, don't you think?

**Comment by abulte** [comment]
Closing this for now, feel free to reopen.
