### ISSUE TITLE
Make the login form localizable

### ISSUE THREAD

**Issue by jphnoel** [opendatateam/udata#626]
The login form uses FlaskLogin, which hard-code some english words in the templates.

The Serbian team managed to localize it with a dirty hack, but it should be possible to do it by configuration.

**Comment by abulte** [comment]
After some initial digging: this issue should be addressed by the [next release of Flask-Security](https://github.com/mattupstate/flask-security/pull/653).

`Flask-Security` nows integrates `Flask-Babelex` and the [field names are translated](https://github.com/mattupstate/flask-security/blob/4aee57d524758b059f36fdde6b3da6d0b202f266/flask_security/forms.py#L29). 

In the mean time, I will work on a PR for the integration w/ `udata` translations. When the next version is released, we'll merge the PR and should be good to go.

NB: we should switch from `Flask-Security-Fork` to `Flask-Security` when the next version is released. [The fork fixes and features seems to have been backported to the original repo](https://github.com/mattupstate/flask-security/pull/617).

**Comment by abulte** [comment]
A French translation has been proposed to flask-security: https://github.com/mattupstate/flask-security/pull/657 (/cc @noirbizarre).
