### ISSUE TITLE
JSON structure change in the API

### ISSUE THREAD

**Issue by tportier** [opendatateam/udata#628]
## Detailed Description

We are integrating the multiple organization search through the API in our client [metaclic](https://github.com/datakode/metaclic) the new name of udatajs ;-)

We identified that the structure of the json returned for a datasets search has changed for the facets : 
**On data.gouv.fr :** 
`"facets": {
    "badge": {
      "terms": [],
      "type": "terms",
      "visible": false
    },
    "extra": null,
    "featured": {
      "false": 3,
      "true": 0,
      "type": "bool",
      "visible": false
    },
    "format": {
      "terms": [
        [
          "shp",
          3
        ],
        [
          "json",
          3
        ]
      ],
      "type": "terms",
      "visible": true
    },`

**On demo.data.gouv.fr :** 
`"facets": {
    "badge": [],
    "featured": [
      [
        false,
        3,
        false
      ]
    ],
    "format": [
      [
        "csv",
        3,
        false
      ],
      [
        "json",
        3,
        false
      ],
      [
        "shp",
        3,
        false
      ]
    ],`

The demo implementation will be the definitive target or do we have to wait a fix?

Thomas

**Comment by tportier** [comment]
@jdesboeufs pour info suite à notre discussion

**Comment by jdesboeufs** [comment]
@davidbgk @vince
It's a breaking change on the API. What can we do ?

**Comment by vince** [comment]
Hi, wrong vince! Unsummoning myself in 3...2...1

**Comment by jdesboeufs** [comment]
Oh sorry!
@odtvince :)
Le mar. 24 janv. 2017 à 21:15, Vince Wadhwani <notifications@github.com> a
écrit :

**Comment by jdesboeufs** [comment]
It's the target implementation. This feature was not really documented yet so we will stay on the same version.

We will inform you when we go live ;)
