### ISSUE TITLE
404 on "Publiez un jeu de données" button from id.data.gouv.fr (login + registration)

### ISSUE THREAD

**Issue by pointbar** [opendatateam/udata#661]
## Detailed Description
The button: "Publiez un jeu de données" provides a 404

## Context
List of contexts where I can view the button: "Publiez un jeu de données"

when I subscribe  
then I receive a mail with this URL:  https://id.data.gouv.fr/register/done

when I'm not login  
then I click on button: "contribuez"  
then I click inside the popup on: "publiez un jeu de données": https://id.data.gouv.fr/login/?next=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fadmin%2Fdataset%2Fnew%2F

**Comment by abulte** [comment]
Closing this in favor of #670
