### ISSUE TITLE
No EDIT button for superadmins on datasets pages

### ISSUE THREAD

**Issue by jdesboeufs** [opendatateam/udata#664]
As a superadmin I have an EDIT button for any organization, but not for datasets. 
Could be very useful to have it too :)

Organization:

<img width="1239" alt="capture d ecran 2017-01-06 a 01 27 22" src="https://cloud.githubusercontent.com/assets/1231232/21703019/75769dc4-d3af-11e6-99f3-393574e95f45.png">

Dataset (same organization):

<img width="1197" alt="capture d ecran 2017-01-06 a 01 28 51" src="https://cloud.githubusercontent.com/assets/1231232/21703044/8a6d81f2-d3af-11e6-993a-e8e1bc13363c.png">

**Comment by davidbgk** [comment]
@jdesboeufs don't you have it at the bottom?

<img width="769" alt="capture d ecran 2017-01-06 a 01 32 33" src="https://cloud.githubusercontent.com/assets/3556/21703111/10dc6078-d3b0-11e6-9ea1-4177a3a7c8da.png">

**Comment by jdesboeufs** [comment]
👍
