### ISSUE TITLE
Replace youckan by the builtin auth

### ISSUE THREAD

**Issue by vinyll** [opendatateam/udata#670]
Youckan is present for historical reasons, when Udata had no builtin auth system and multiple Etalab apps had to connect to an SSO.

These apps were removed and since then udata has a builtin login system with SSO capabilities.

We may therefore consider removing Youckan, canceling id.data.gouv.fr development and promote the usage of the internal login system.

**Comment by jdesboeufs** [comment]
Maybe related to https://github.cometalab/udata-gouvfr?

**Comment by odtvince** [comment]
@jdesboeufs Yes it is, but we centralise the issues here for now

**Comment by jdesboeufs** [comment]
Ok! I was not sure since @noirbizarre decides to track the next production
deployment in etalab/udata-gouvfr#141.

**Comment by noirbizarre** [comment]
Sorry I missed the discussion.
Until now, we have:
- core/common issues and enhancements are tracked on opendatateam/udata
- extension specifics issues and enhancements are tracked on each repository
- Data.gouv.fr issues, infrastructure changes... are tracked on etalab/udata-gouvfr repository but it is subject to discussion, it might be on an internal repository or whatever. I don't think it's pertinent to put these on opendatateam/udata

**Comment by abulte** [comment]
Added the `ready` label because this is almost OK on @noirbizarre's side (I think).
