### ISSUE TITLE
Some images uploaded by users are missing

### ISSUE THREAD

**Issue by odtvince** [opendatateam/udata#671]
The following reuse is referencing an image that was uploaded by the user: https://www.data.gouv.fr/fr/reuses/liste-agregee-de-prenoms-et-grilles-de-jeux-pour-chaque-prenom/

There is no image anymore at: https://www.data.gouv.fr/s/images/2015-07-09/f9b419570b4b4c52841d33a0aeff2ac1/camille.15x15.promo.png

This should not be possible. Further investigation needed.

**Comment by abulte** [comment]
@vince any new occurence of this problem?

**Comment by vince** [comment]
@abulte I think you are summoning the wrong Vince.

**Comment by abulte** [comment]
@vince yes sorry, my bad!

**Comment by abulte** [comment]
@odtvince any new occurence of this problem?
