### ISSUE TITLE
Silent fail when trying to create a reuse with a long title

### ISSUE THREAD

**Issue by jdesboeufs** [opendatateam/udata#676]
When I try to create a reuse with a very long name, I'm not able to click on the next button.
Behind the scene, the POST request ends with a 500 error (without any detail).

- [ ] API should respond with a 400 error, with validation error details.
- [x] Admin should display some information to the end-user.

Env: next

**Comment by noirbizarre** [comment]
The 400 are already handled, the issue is the 500 that shouldn't happen.

**Comment by jdesboeufs** [comment]
👍 so the second point will be trivial :)
