### ISSUE TITLE
uData Telco 

### ISSUE THREAD

**Issue by petzlux** [opendatateam/udata#679]
Hi,

Just a little bit desperate to get some feedback from the etalab team. At the Elysee Hackathon, we had arranged for a telco to discuss international cooperation on uData. 
Sadly, it was only myself and @jdjak from Serbia that were there in Gitter on Jan 4th 16h00  . 

@noirbizarre I tried emailing you about it, but go no reply. Can we please have an answer on how we can progress our collaboration in 2017 and if we can rearrange a telco.

Thanks

**Comment by odtvince** [comment]
Hi @petzlux ,

We are very sorry for missing you and @jdjak on Gitter on Jan 4th 16h00.

We were in the last meters of the race to prepare for the opening of the French company register (it went live during the night from Jan 4th to Jan 5th). This was a very important milestone (and a very large dataset). We served more than 2TB in the first hours after the opening. We were so absorbed by everything that had to be ready for the grand opening that we forgot our planned meeting. I apologize again for leaving you alone on Gitter.

Would you be available at the same time (16h00) on the same day (Wednesday) this week instead?

Sorry again

**Comment by noirbizarre** [comment]
Hi @petzlux 

I'm really sorry too !! Like @odtvince said, we were in a rush and we forgot !

Sincere apologize, to you and @jdjak

@odtvince : OK for me

**Comment by petzlux** [comment]
I'll close this issue now as I now have both the group email and Vincent's email, and have proposed a new date for the telco. 

Hope to catch up with you on the 18th ! And good luck for the 1.0 release, looks like you are working hard on it!
