### ISSUE TITLE
Switch to Chart.js 2.0 or something else

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#713]
## Detailed Description
The current chart implementation rely on the Chart.js 1.0 which is not maintained anymore.
It lacks some previously used chart type (stacked chart...)

## Context
Upgrading to Chart.js 2.0 will provides support, missing charts, the ability to remove some unmaintained depency for extra charts which are now builtins.

Another possibility is to use Vue.js to draw raw svg.

**Comment by noirbizarre** [comment]
Reverted until further fixes

**Comment by abulte** [comment]
Closed by #1352
