### ISSUE TITLE
Order talks on datasets by decreasing date (last first)

### ISSUE THREAD

**Issue by cquest** [opendatateam/udata#737]
When there is a lot of talks about a dataset, the list gets long and the last questions appear at the bottom of the list. It should be better to have them on top like ressources ordered with last on top.

Example: http://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/

**Comment by davidbgk** [comment]
To me, we should stick to the chronological order since it's a comment-like interaction. *If* we switch one day to something in the vein of timeline-like interactions it would make sense though.

**Comment by taniki** [comment]
I agree with @davidbgk for consistency reasons but we need to decide that collectively.

cc @thimy  @pblayo @oncletom

**Comment by abulte** [comment]
Done.
