### ISSUE TITLE
Establish some vue component naming convention

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#753]
## Detailed Description
Currently there is no Vue component naming convention and some inconsistency. ex:

```
IssueList  < issues/list
DiscussionList < discussions/list
FollowerList < follow/list
…
DatasetCards < dataset/card-list
...
FormHorizontal < form/horizontal-form.vue
```

## Context
As a developper, I want a clear and consistent naming convention so:
- I can create new component with consisten naming
- I can find existing components easily
- Search and find in code is effective

## Possible Implementation
To be defined

**Comment by abulte** [comment]
Migrating this to https://github.com/opendatateam/udata/issues/1312
