### ISSUE TITLE
Special characters fails on API

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#762]
## Detailed Description
Any non ascii character fail on API (mostly visible on suggest API and OAuth).

[See this as example](https://sentry.data.gouv.fr/share/issue/332e3332/)

This is related to oauthlib query parsing

## Context
udata perform full text search and in France, special characters are essentials so this should be fixed ASAP !

## Possible Implementation
Make a PR to fix:
- idan/oauthlib#414
- idan/oauthlib#426

## Your Environment
- udata 1.0.1

**Comment by r4fek** [comment]
Hi! Any plans to fix it soon?

**Comment by abulte** [comment]
This is OK on suggest API as far as I can see, but we still have a problem on OAuth? What's the reproduction scenario for this? /cc @noirbizarre

**Comment by noirbizarre** [comment]
Already fixed (switch from `oauthlib` to `authlib`
