### ISSUE TITLE
Placeholder for territories is not displayed in search suggestion

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#787]
<img width="515" alt="capture d ecran 2017-02-20 a 21 13 00" src="https://cloud.githubusercontent.com/assets/3556/23148070/701c7f1c-f7b1-11e6-9a5d-615cc2827399.png">

`img/placeholder_territory.png` should be rendered from udata-fr

**Comment by noirbizarre** [comment]
Fixed by #792
