### ISSUE TITLE
Add cache on zones and discussions views call

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#796]
Otherwise a repeated view refetch these resources:
https://www.webpagetest.org/result/170222_C5_MSWY/1/details/cached/#waterfall_view_step1

**Comment by abulte** [comment]
@davidbgk is this still in progress?

**Comment by davidbgk** [comment]
@abulte I gave up participating on the project after https://github.com/opendatateam/udata/pull/802 so, sadly, no progress whatsoever…

**Comment by abulte** [comment]
@davidbgk thanks for the update ;-)

**Comment by noirbizarre** [comment]
Already done on reverse proxy level for zones
