### ISSUE TITLE
Change the Content-Type header for woff2 files

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#797]
(détecté : application/octet-stream | conseillé : application/font-woff2)

https://www.dareboost.com/fr/report/58ad9fbb0cf233f4d567838e

**Comment by davidbgk** [comment]
I added to the `nginx/mime.types` file:

```
	application/x-font-ttf         	ttf;
	font/opentype                   otf;
	application/vnd.ms-fontobject   eot;
	font/x-woff                     woff;
	font/woff2                      woff2;
```

to the `slb-common` repo, r? @noirbizarre

**Comment by noirbizarre** [comment]
👍

**Comment by davidbgk** [comment]
Internal config.
