### ISSUE TITLE
Numbers of followers doesn't decrease on admin panel when unfollow

### ISSUE THREAD

**Issue by Ydrasil** [opendatateam/udata#819]
On dev, when we unfollow (a organization for instance) it doesn't update correctly the numbers of followers on the admin panel.

## Detailed Description

When we unfollow, it must update correctly the number of followers

## Context

When I unfollow a organization, I want that the number of follow is correct, so I can have a good vision on how many follow I have.

## Possible Implementation

Decrease the number of follow of 1 on update when we unfollow

## Your Environment

* Browser Name and version: 51.0.1
* Operating System and version (desktop or mobile): Ubuntu 16.04.1

**Comment by abulte** [comment]
Migrating this to https://github.com/opendatateam/udata/issues/1308, thanks for the details.
