### ISSUE TITLE
Number of followed isn't correct on /users/{userName}

### ISSUE THREAD

**Issue by Ydrasil** [opendatateam/udata#820]
On dev, When I follow an organization its shows me that I have 0 followed.

## Detailed Description

When we go on our page (/users/{userName}) it must show the correct number of followed.

## Context

When go on my page , I want to see the correct number of followed, so I can see without clicking anywhere how many followed I have.

## Possible Implementation

Search and set the numbers of followed on /users/{userName}

## Your Environment

* Browser Name and version: 5.10.1
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by abulte** [comment]
Migrating this to https://github.com/opendatateam/udata/issues/1308
