### ISSUE TITLE
Unable to retrieve full size organization logo from API

### ISSUE THREAD

**Issue by jdesboeufs** [opendatateam/udata#824]
The API returns an URL to a resized image (100x100):
https://www.data.gouv.fr/api/1/organizations/54da1f52c751df59f7467389/

The regular organization page display the full size image:
https://www.data.gouv.fr/fr/organizations/grand-poitiers-open-data/

Consequently we are forced to display a low resolution image in our geo-specific portal:
https://inspire.data.gouv.fr/datasets/e80d3d24c0540868a5656ab8bb91b66af24b80e4

**Comment by davidbgk** [comment]
You have to deal with that line:
https://github.com/opendatateam/udata/blob/2be043bfe18d74859d4a03f40238a099eba99a56/udata/core/organization/api_fields.py#L74

Not sure why it only returns a thumbnail though, there is probably something to understand here:
https://github.com/opendatateam/udata/blob/2be043bfe18d74859d4a03f40238a099eba99a56/udata/core/organization/models.py#L117-L119

**Comment by jdesboeufs** [comment]
Still not working when it's an embedded resource.

**Comment by jdesboeufs** [comment]
https://www.data.gouv.fr/api/1/datasets/55130617c751df78f8cea129/
See `organization` node.
