### ISSUE TITLE
Site badges metrics

### ISSUE THREAD

**Issue by noirbizarre** [opendatateam/udata#893]
## Detailed Description
It would be interesting to have some site badges metrics because some badges are major indicators.

## Context
Badges metrics have been removed in #887 because they were not in use but they were breaking some command (#885).
I could be interesting to have some site wide metrics on badges by model.
As example, it would be interesting to have the number of public services (ie. number of dataset having the `public service` badge)

**Comment by abulte** [comment]
We have the number of public badges here https://www.data.gouv.fr/api/1/metrics/data.gouv.fr?id=data.gouv.fr&cumulative=true
