### ISSUE TITLE
Admin: visual feedback on collapsed items within the Quality block

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#915]
<img width="628" alt="capture d ecran 2017-05-24 a 11 36 49" src="https://cloud.githubusercontent.com/assets/3556/26411998/64613b1a-4075-11e7-9004-b0e37d098968.png">

E.g.: here the Description is collapsed but there is no visual feedback that it could be expanded to see details.

**Comment by abulte** [comment]
Fixed by #945
