### ISSUE TITLE
Admin: the up-to-date entry within the quality block is wrong

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#916]
<img width="639" alt="capture d ecran 2017-05-24 a 11 40 16" src="https://cloud.githubusercontent.com/assets/3556/26412179/e3b6bf70-4075-11e7-89e4-dc0fa6bcfcff.png">

Does it require an update or not? It happens on `/fr/admin/dataset/57f0b8f088ee3808545ff490/` for instance. It looks to be a bug related to the interpretation of 0 (zero) on the JS side.

**Comment by thimy** [comment]
It seems `quality` doesn't have a `update_in` property, which makes the condition `false` no matter what.
