### ISSUE TITLE
Admin: spatial coverage has a hand on hover but no way to move the map

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#917]
<img width="627" alt="capture d ecran 2017-05-24 a 11 42 58" src="https://cloud.githubusercontent.com/assets/3556/26412288/3d68435e-4076-11e7-8253-a482b4f0a990.png">

Not sure if we should remove the hand cursor or let the user move the map?

**Comment by abulte** [comment]
Remove the and IMHO.

**Comment by taniki** [comment]
![peek 2017-12-11 11-25](https://user-images.githubusercontent.com/27315/33826757-51bb3c7e-de66-11e7-9362-569dd6758dbe.gif)
