### ISSUE TITLE
Admin: spatial coverage hovering France will display tooltip on Guyane

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#918]
<img width="627" alt="capture d ecran 2017-05-24 a 11 45 02" src="https://cloud.githubusercontent.com/assets/3556/26412365/8b8e8db8-4076-11e7-9e42-101d4bc61725.png">

Not sure if it's on our side or on leaflet one but it's annoying, to be verified on other use case, happens with `/fr/admin/dataset/57f0b8f088ee3808545ff490/` for instance.

**Comment by ThibaudDauce** [comment]
I don't think we show this map anymore. Feel free to re-open if it's still an issue
