### ISSUE TITLE
Admin: dashboard displays "1 réutilisations" when it should be singular

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#920]
## Detailed Description
In the dashboard summary boxes, the "réutilisation" word is always pluralized even when there is only one.
There's probably the same issue with "jeux de données" and "abonnés".

## Possible Implementation
Do we have an i18n tool that can handle singular and plural?

**Comment by abulte** [comment]
Closed this due to lack of activity. Feel free to reopen if this is still an issue.
