### ISSUE TITLE
Admin: icons overflow on hover

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#921]
![image](https://cloud.githubusercontent.com/assets/1301085/26413110/3a4fad3a-40ab-11e7-9532-d907e5f3c359.png)

## Detailed Description
When hovering on dashboard summary boxes, the icons zoom and overflow from their box.

## Possible Implementation
Set `overflow: hidden` to the box.

**Comment by abulte** [comment]
Fixed by #921
