### ISSUE TITLE
Admin: traffic is at zero for the Etalab organization

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#923]
<img width="1266" alt="capture d ecran 2017-05-24 a 11 53 47" src="https://cloud.githubusercontent.com/assets/3556/26412735/bc3646bc-4077-11e7-9b3d-0a825dffa134.png">

The legend lacks some CSS in production but is present on the `dev` branch. Note that I have no graph at all with Firefox on the `dev` branch though.

**Comment by noirbizarre** [comment]
Duplicate #896 
Fix seems to be on the udata-piwik side

**Comment by abulte** [comment]
Closing in favor of #896

**Comment by abulte** [comment]
Actually, in favor of https://github.com/opendatateam/udata-piwik/issues/16
