### ISSUE TITLE
Admin: some panels have a top border and some other don't

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#924]
![image](https://cloud.githubusercontent.com/assets/1301085/26413086/2547ab22-40ab-11e7-8595-de9f32a69a51.png)

## Detailed Description
The dashboard panels don't have a consistent appearance and one might wonder about that border.

## Context
If the border means the panel is editable, it doesn't seem relevant to me to differenciate them with a border, we should rather keep them consistent.

## Possible Implementation
Maybe an edit icon would be enough?

**Comment by taniki** [comment]
agreed with @thimy. the border is a too subtle hint to be understandable

**Comment by abulte** [comment]
Closed this due to lack of activity. Feel free to reopen if this is still an issue.
