### ISSUE TITLE
Admin: height of step-blocks on dataset (etc) addition is not consistent w/ small resolutions

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#925]
<img width="921" alt="capture d ecran 2017-05-24 a 11 57 34" src="https://cloud.githubusercontent.com/assets/3556/26412935/5ba6dd42-4078-11e7-8d51-df8f1ff6367f.png">

The displayed block should take all the height of the top bar.

**Comment by abulte** [comment]
Fixed by #938
