### ISSUE TITLE
Admin: typo in "ce champs est requis"

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#926]
![image](https://cloud.githubusercontent.com/assets/1301085/26413005/dfdd18a6-40aa-11e7-9eb8-9f47a81f2644.png)

## Detailed Description
When we try to validate a form and forget an required field, we get the sentence "ce champs est requis".
The word "champs" shouldn't have an _s_ at the end.

**Comment by abulte** [comment]
Ok on `master` as of today.
