### ISSUE TITLE
Admin: consistency of select vs. input given the browser

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#927]
With Webkit:

<img width="869" alt="capture d ecran 2017-05-24 a 12 01 08" src="https://cloud.githubusercontent.com/assets/3556/26413062/c62eb16c-4078-11e7-81d1-0301fdb24999.png">

With Gecko:

<img width="982" alt="capture d ecran 2017-05-24 a 12 01 18" src="https://cloud.githubusercontent.com/assets/3556/26413074/d012779a-4078-11e7-91d6-affe9dbbcd73.png">

**Comment by abulte** [comment]
@davidbgk you mean the style of the dropdown arrow across browsers?

**Comment by davidbgk** [comment]
Honestly, I don't remember exactly which makes it a bad bug report :(

Maybe the consistency on rounded corners too?

**Comment by abulte** [comment]
Basically you'd like the Webkit select style across browsers?

**Comment by davidbgk** [comment]
I think it was during the workweek while performing a full admin review with @thimy, do you remember anything else @thimy ?

**Comment by abulte** [comment]
Closing this for now, not very clear, do not hesitate to reopen if needed.

IMHO native styles different between browsers are not a serious problem.
