### ISSUE TITLE
Admin: when a backend error occurred, it remains displayed the whole creation process

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#929]
If you insert an already existing URL for a reuse, you get a Sentry ID:

<img width="1013" alt="capture d ecran 2017-05-24 a 12 04 31" src="https://cloud.githubusercontent.com/assets/3556/26413241/533dfe3c-4079-11e7-8102-9ce37d9e3661.png">

When modified and resubmitted with success, you still get it on the next step of the process:

<img width="1028" alt="capture d ecran 2017-05-24 a 12 04 51" src="https://cloud.githubusercontent.com/assets/3556/26413266/6c1ebe32-4079-11e7-95b6-9fd6c1db3f61.png">

It should be hidden once fixed.

**Comment by abulte** [comment]
No more sentry id on `master` as of now.

<img width="801" alt="capture d ecran 2017-11-13 14 46 11" src="https://user-images.githubusercontent.com/119625/32728650-6a552592-c881-11e7-880e-0f6ecb6284ba.png">
