### ISSUE TITLE
Admin: no visual feedback on required image for reuse creations

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#930]
<img width="1030" alt="capture d ecran 2017-05-24 a 12 08 06" src="https://cloud.githubusercontent.com/assets/3556/26413346/bc4603fc-4079-11e7-98b5-21c0143d5d20.png">

Clicking the Next button does not have any impact, an error message should be displayed (and the button greyed until then?)

**Comment by abulte** [comment]
Greyed out on `master` as of today.
