### ISSUE TITLE
Unable to join a organization

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#931]
## Detailed Description
When trying to join an organization, clicking the button does nothing.

## Context
As (it seemed to me) we can only join an organization from page on the front, it would be problematic if this button doesn't work.

## Possible Implementation
It could be cause by the tooltip overflowing the button.

**Comment by abulte** [comment]
@thimy it's OK for me on `dev`, can you check again?

**Comment by thimy** [comment]
Seems to work indeed.
