### ISSUE TITLE
Admin : saving an edited harvester does not work

### ISSUE THREAD

**Issue by odtvince** [opendatateam/udata#949]
## Detailed Description
As an admin, trying to edit a pre-existing harvester (like fixing the url on https://www.data.gouv.fr/fr/admin/harvester/5631ef2988ee3837ce531585/edit ), a javascript error is fired when one try to save: 
`TypeError: this.source.update is not a function`

## Your Environment
any browser

**Comment by noirbizarre** [comment]
Already fixed in #817 by 33e7ed98f541eece6fe5bdaedc5841d568046a40
