### ISSUE TITLE
I am unsure about what to do with the Procfile.sample

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#977]
I am discovering the project by installing it for the first time.

1. System Dependencies install with Docker = 👍 
1. Local Dependencies install on macOS = 👍 

However I feel a bit lost when I am about to launch it when I am asked to modify the `Procfile`.  I am going to deconstruct my discomfort:

```
## Uncomment lines given your setup and workflow.
```

What is meant by _workflow_? The term is new at this stage.

```
## That first line actually launch the local web server,
## we prefer to do that manually to avoid mixing these
## logs with all other dependencies but YMMV
```

It seems a personal choice is expressed – I don't know if I should uncomment the line or not.
Plus I was not aware of the meaning of the _YMMV_ acronym so I got a bit side tracked looking after its meaning.

Decision: I will uncomment it but mostly because everything is commented out — I have to start somewhere.

```
## Launch Celery workers (required)
# worker: inv work
# beat: inv beat
```

They seem required although they are commented out. Should they be uncommented by default?

## Possible Implementation

To be honest, I would have rather had something ready to start and just have a choice between a few commands to run to avoid having to copy/modify a file:

- `honcho start` for a general use case
- `honcho start --procfile Procfile.docker` if using Docker
- possibly `honcho start --procfile Procfile.services` to launch system deps separately, as _they_ are really the only ones requiring an edit of the Procfile (if the services are not already launched on system boot)

## Your Environment

* Browser Name and version: N/A
* Operating System and version (desktop or mobile): macOS 10.12 w/ homebrew + Docker

**Comment by abulte** [comment]
@oncletom Great feedback as a first time user! FIY I had a discussion with @noirbizarre about removing `honcho` and thus `Procfile.sample`. Docker should probably the preferred way to have something setup locally as fast and easily as possible.

**Comment by davidbgk** [comment]
Making Docker a dependency of the project doesn't look good to me, let's discuss this during the workweek.

**Comment by abulte** [comment]
It would be a dependency as such IMHO (just like it isn't one now, even though we have a `docker-compose.yml`), just a way to launch the project quickly. It would still be possible (and documented) to install the solution "manually". But yeah, let's discuss this next week in depth!

**Comment by abulte** [comment]
@oncletom maybe we can close this? `honcho` has been removed.
