### ISSUE TITLE
DistributionNotFound: The 'udata' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#978]
I typed `honcho start` and I face the aforementioned error when I open 

## Detailed Description

An error page is displayed with a stack trace:

```
pkg_resources.DistributionNotFound
  DistributionNotFound: The 'udata' distribution was not found and is required by the application
```

<img width="1020" alt="screen shot 2017-06-14 at 18 38 53" src="https://user-images.githubusercontent.com/138627/27144046-bcf01dac-5130-11e7-9725-ac42ffde5bb3.png">

I subsequently ran `udata init` and I managed to see the homepage.

So in the end the _Everything is up and running!_ is a bit misleading.

And I also wonder why I do have to fetch licenses with the `udata licenses ...` command? Could it be part of `udata init`? Likewise with `tx pull` and `inv i18nc`.

## Context

When am reading http://udata.readthedocs.io/en/latest/running-project/ , I want to start udata , so I can see a landing page with no datasets (or with a welcome message).

## Possible Implementation

1. Run database migrations, translations and, 18n and stuff at once, at first
1. Let the user start the app without displaying an error
1. Let the user populate the database with dummy datasets to see what it could look like with their data

```bash
$ udata first-time-init
$ honcho start
$ udata insert-dummy-datasets
```

Something like that.

## Your Environment

* Browser Name and version: N/A
* Operating System and version (desktop or mobile): macOS 10.12 + Docker +

**Comment by abulte** [comment]
@oncletom Which branch are you using? I think on `dev` the licences pull is part of the init (#950) and in general the init command is better.

**Comment by oncletom** [comment]
@abulte I checked out the default branch — master. I guess `dev` is the one we should work on?

**Comment by abulte** [comment]
@oncletom normally it's `master` but those days `dev` is quite far ahead.

**Comment by oncletom** [comment]
I am happy to close this issue and to reopen it if I encounter a similar problem on `dev` branch.
