### ISSUE TITLE
Datasets and Members links in top right corner of org page are inactive

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#983]
## Detailed Description

<img width="764" alt="screen shot 2017-06-19 at 09 13 04" src="https://user-images.githubusercontent.com/138627/27275501-91cf3f0c-54cf-11e7-867c-c9d7e30f3c7d.png">

A click in the top right corner links for datasets and members does not behave like the "Jeux de données" and "Members" tabs do (bottom left corner of the screenshot).

## Context

When I click on x members , I want to see the members of the organisations.

## Possible Implementation

N/A

## Your Environment

* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): macOS 10.12.5

PS: I am happy to tackle it to have a better understand of the frontend and such 👍

**Comment by oncletom** [comment]
@davidbgk happy to pair on this one too :-) @thimy do you fancy joining us too?

**Comment by noirbizarre** [comment]
Fixed by #1997
