### ISSUE TITLE
Normalize formats for resources’ files

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#986]
For now we have (result of [csvstats](http://csvkit.readthedocs.io/en/1.0.2/scripts/csvstat.html)):

```
14. "format"

	Type of data:          Text
	Contains null values:  True (excluded from calculations)
	Unique values:         291
	Longest value:         158 characters
	Most common values:    JSON (16396x)
	                       SHP (15041x)
	                       ZIP (13379x)
	                       csv (4049x)
	                       XLS (3446x)
```

We can at least clean up the lower/upper case issue but even better restrict that field to known/popular ones (longest value 😱).

Note: do not forget to propose `JSON within a Zip` and so on which are popular and descriptive too.

**Comment by abulte** [comment]
Linked to #1045
