### ISSUE TITLE
Weird + (plus) sign when more than two terms in search input

### ISSUE THREAD

**Issue by davidbgk** [opendatateam/udata#987]
See:

<img width="445" alt="plus-sign" src="https://user-images.githubusercontent.com/3556/27343073-c335bb24-55d9-11e7-8303-8b3717798c54.png">

Plus signs shouldn't be there between bar baz and quux. It happens on `next.dgfr` too.

**Comment by oncletom** [comment]
@davidbgk fancy pairing on this one today?

**Comment by oncletom** [comment]
@abulte spotted the reason of why this behaviour happens.

Cf. [String.prototype.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Using_global_and_ignore_with_replace()), it replaces only once unless a `global` flag is added.

Moving from `replace('+', '')` to `replace(/\+/g), '')` would work but I'm concerned about _if_ the user types a + sign for some reason. Why are the `+` signs added in the first place and how do we distinguish them from a user input?

**Comment by abulte** [comment]
Ok thanks. I will look into the serialization on the server side, maybe we could get something more robust (`%20`?).

**Comment by oncletom** [comment]
@abulte indeed — it would be sensible we use the same encoding/decoding mecanism.

```js
# When we submit to the server
encodeURIComponent('foo bar baz quux')
> "foo%20bar%20baz%20quux"

# When we read from the URL
decodeURIComponent('foo%20bar%20baz%20quux')
"foo bar baz quux"
```
