### ISSUE TITLE
Lack of consistency between user profile empty states

### ISSUE THREAD

**Issue by thimy** [opendatateam/udata#995]
![image](https://user-images.githubusercontent.com/1301085/27489614-09e1f8ac-5833-11e7-94c8-f79b5e27cc46.png)

![image](https://user-images.githubusercontent.com/1301085/27489351-1fc9a076-5832-11e7-8b7d-fc37b8f9a885.png)

![image](https://user-images.githubusercontent.com/1301085/27489364-2ae67fa6-5832-11e7-8e89-5aa426711781.png)

The sections of a user profile differ from one to another, some don't event display an empty state.

We could add a button to create a dataset or a reuse on the appropriate sections.

**Comment by taniki** [comment]
The consistency has been fixed but there is still room for improvement regarding adding nudges to add new stuff.
